function actradi() % autogenerated function wrapper
%
% This code is responsible for the activation (enable, on) of the radius input
% in crcparain.m.
% Francesco Pacchiani 6/2000
%
%
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals
if ic == 2

    set(input4, 'enable', 'on');
    set(tx6, 'color', 'k');

else

    set(input4, 'enable', 'off');
    set(tx6, 'color', 'w');

end

end
