%
% Creates the input window for the parameters needed in order to compute the
% spatial variation of the correlatiin dimension. Called from startfd.m (org=10).
%
%
figure_w_normalized_uicontrolunits('Units','pixel','pos',[200 400 550 300 ],'Name','Parameters','visible','off',...
    'NumberTitle','off','MenuBar','none','Color',[c1 c2 c3],'NextPlot','new');
axis off;

input1 = uicontrol('Style','edit','Position',[.75 .85 .19 .06],...
    'Units','normalized','String',num2str(dim),...
    'Callback','dim=str2double(get(input1,''String'')); set(input1,''String'',num2str(dim));');

input2 = uicontrol(,'Style','popupmenu','Position',[.75 .70 .23 .06],...
    'Units','normalized','String','Automatic Range|Manual Fixed Range|Manual',...
    'Value',1,'Callback','range=(get(input2,''Value'')); set(input2,''Value'',range), actrange');

input3 = uicontrol('Style','edit','Position',[.34 .45 .10 .06],...
    'Units','normalized','String',num2str(radm), 'enable', 'off',...
    'Value',1,'Callback','radm=str2double(get(input3,''String'')); set(input3,''String'', num2str(radm));');

input4 = uicontrol('Style','edit','Position',[.75 .45 .10 .06],...
    'Units','normalized','String',num2str(rasm), 'enable', 'off',...
    'Value',1,'Callback','rasm=str2double(get(input4,''String'')); set(input4,''String'', num2str(rasm));');

%input5 = uicontrol(,'Style','popupmenu','Position',[.75 .30 .23 .06],...
%   'Units','normalized','String','Earthquake Catalog|Random Catalog',...
%   'Value',1,'Callback','cat=(get(input5,''Value'')); set(input5,''Value'',cat)');


tx1 = text('EraseMode','normal', 'Position',[0 .95 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String',' Dimension of the Interevent Distances (2 or 3): ');

tx2 = text('EraseMode','normal', 'Position',[0 .75 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String',' Distance Range within which D is computed: ');

tx3 = text('EraseMode','normal', 'Position',[0 .45 0], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Minimum value: ', 'color', 'w');

tx4 = text('EraseMode','normal', 'Position',[.52 .45 0], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Maximum value: ', 'color', 'w');

tx5 = text('EraseMode','normal', 'Position',[.41 .45 0], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','km', 'color', 'w');

tx6 = text('EraseMode','normal', 'Position',[.94 .45 0], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','km', 'color', 'w');

%tx7 = text('EraseMode','normal', 'Position',[0 .25 0 ], 'Rotation',0 ,...
%   'FontSize',fontsz.m , 'FontWeight','bold' , 'String',' Nature of Catalog  ');

close_button=uicontrol('Style','Pushbutton',...
    'Position',[.60 .05 .20 .12 ],...
    'Units','normalized','Callback','close;zmap_message_center.set_info('' '','' '');done','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.20 .05 .20 .12 ],...
    'Units','normalized',...
    'Callback','close;think; sel = ''ca''; Dcross;',...
    'String','Go');


set(gcf,'visible','on');
watchoff;
