%
% Input window for the random catalogue parameters in spherical geometry.
% Called from startfd.m.
%
%
%disp('fractal/codes/rndsphparain.m');
%
%
% Creates the input window
%
figure_w_normalized_uicontrolunits('Units','pixel','pos',[150 100 350 350 ],'Name','Parameters for the sphere','visible','off',...
    'NumberTitle','off','MenuBar','none','Color',[c1 c2 c3],'NextPlot','new');
axis off;

input1 = uicontrol('Style','edit','Position',[.70 .90 .22 .06],...
    'Units','normalized','String',num2str(radiusx),...
    'Callback','radiusx = str2double(get(input1,''String'')); set(input1,''String'',num2str(radiusx));');

input2 = uicontrol('Style','edit','Position',[.70 .8 .22 .06],...
    'Units','normalized','String',num2str(radiusy),...
    'Callback','radiusy = str2double(get(input2,''String'')); set(input2,''String'',num2str(radiusy));');

input3 = uicontrol('Style','edit','Position',[.70 .7 .22 .06],...
    'Units','normalized','String',num2str(radiusz),...
    'Callback','radiusz = str2double(get(input3,''String'')); set(input3,''String'',num2str(radiusz));');

input4 = uicontrol('Style','edit','Position',[.70 .6 .22 .06],...
    'Units','normalized','String',num2str(centerx),...
    'Callback','centerx = str2double(get(input4,''String'')); set(input4,''String'',num2str(centerx));');

input5 = uicontrol('Style','edit','Position',[.70 .5 .22 .06],...
    'Units','normalized','String',num2str(centery),...
    'Callback','centery=str2double(get(input5,''String'')); set(input5,''String'',num2str(centery));');

input6 = uicontrol('Style','edit','Position',[.70 .4 .22 .06],...
    'Units','normalized','String',num2str(centerz),...
    'Callback','centerz=str2double(get(input6,''String'')); set(input6,''String'',num2str(centerz));');



tx1 = text('EraseMode','normal', 'Position',[0 1.00 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Radius of sphere in x [deg]: ');

tx2 = text('EraseMode','normal', 'Position',[0 .88 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Radius of sphere in y [deg]: ');

tx3 = text('EraseMode','normal', 'Position',[0 .76 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Radius of sphere in z [km]: ');

tx4 = text('EraseMode','normal', 'Position',[0 .64 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String',' Center Coordinate x [deg]: ');

tx5 = text('EraseMode','normal', 'Position',[0 .515 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Center Coordinate y [deg]: ');

tx6 = text('EraseMode','normal', 'Position',[0 .39 0 ], 'Rotation',0 ,...
    'FontSize',fontsz.m , 'FontWeight','bold' , 'String','Center Coordinate z [km]: ');


close_button=uicontrol('Style','Pushbutton',...
    'Position',[.60 .10 .25 .10 ],...
    'Units','normalized','Callback','close;welcome('' '','' '');done','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.20 .10 .25 .10 ],...
    'Units','normalized',...
    'Callback','close;think; rndsph = ''distr3b''; dorand;',...
    'String','Go');



set(gcf,'visible','on');
watchoff;
