function startfd(org, gobut) % autogenerated function wrapper
%
% This is the starting code for the fractal dimension, which organizes
% the different codes with each other.
% Francesco Pacchiani 1/2000
%
%
% disp('fractal/codes/startfd.m');
%
%
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals
switch (org)

    case 1 	% Call from timeplot.m, fdsphere.m, dorand.m

        range = 1;
        radm = [];
        rasm = [];
        fdparain(gobut);


    case 2	% Call from fdparain.m

        dtokm = 1;
        pdc3;


    case 3	% Call from timeplot.m
        %
        % Default values
        %
        numran = 1000;				% # of points in random catalog
        distr = 1;
        stdx = 0.5;
        stdy = 0.5;
        stdz = 1;
        long1 = min(ZG.primeCatalog.Longitude);
        long2 = max(ZG.primeCatalog.Longitude);
        lati1 = min(ZG.primeCatalog.Latitude);
        lati2 = max(ZG.primeCatalog.Latitude);
        dept1 = min(abs(ZG.primeCatalog.Depth));
        dept2 = max(abs(ZG.primeCatalog.Depth));

        E = ZG.primeCatalog;
        randomcat;


    case 4	% Call from timeplot.m

        nev = 600;
        inc = 100;
        fdtimin;


    case 5  % Call from view_Dv.m

        range = 1;
        radm = [];
        rasm = [];
        crclparain;

end	%end switch(org)



end
