function cluticut(var1)
    % cluticut.m                             A.Allmann
    % function to select equivalent events which are in a certain time window
    % and build a new catalog with eqs in this clusters
    % or select eq in a certain time window in a single cluster
    %
    % last modification 8/95

    global mess te1 fontsz winx winy sys term wex wey welx wely
    global tmp1 tmp2 eqtime bg ttcat tt1cat cluslength
    global freq_field1 freq_field2 close_button go_button
    global backbgevent original equi bgevent backequi clu newclcat backcat
    global equi_button bg_button clu1 mouse_button
    global plot1_h plot2_h file1 clust clsel new


    if var1==2 | var1==4
        tmeq=clustime(2);
        tmeqtime=tmeq-tmeq(1);
    end

    if var1==1 | var1==2
        figure_w_normalized_uicontrolunits(mess)
        clf
        set(gca,'visible','off');
        set(gcf,'visible','off');
        set(gcf,'Name','Time Selection');
        if var1==2
            tmp2=0;
        else
            tmp2=original(clust(1,equi(1,10)),3);
        end
        freq_field1= uicontrol('Style','edit',...
            'Position',[.80 .60 .17 .10],...
            'Units','normalized','String',num2str(tmp2),...
            'Callback','tmp2=str2double(get(freq_field1,''String'')); set(freq_field1,''String'',num2str(tmp2));');

        tmm=equi(length(equi(:,1)),10);

        if var1==2
            tmp1=tmeqtime(length(tmeqtime));
        elseif var1==1
            tmp1=original(clust(cluslength(tmm),tmm),3);
        end
        freq_field2=uicontrol('Style','edit',...
            'Position',[.80 .40 .17 .10],...
            'Units','normalized','String',num2str(tmp1),...
            'Callback','tmp1=str2double(get(freq_field2,''String'')); set(freq_field2,''String'',num2str(tmp1));');


        close_button=uicontrol('Style','Pushbutton',...
            'Position', [.70 .05 .15 .15 ],...
            'Units','normalized','Callback','welcome;done','String','Cancel');

        if var1==1
            go_button=uicontrol('Style','Pushbutton',...
                'Position',[.27 .05 .15 .15 ],...
                'Units','normalized',...
                'Callback','welcome;done;cluticut(3);',...
                'String','Go');
            ticut_info=uicontrol('Style','Pushbutton',...
                'Position',[.49 .05 .15 .15 ],...
                'Units','normalized',...
                'Callback','clinfo(11);',...
                'String','Info');
            mouse_button=uicontrol('Style','Pushbutton',...
                'Position',[.06 .05 .15 .15 ],...
                'Units','normalized',...
                'Callback','cltiplot(1);[tmp2,tmp1]=timeselect(1);cluticut(3);cltiplot(3);',...
                'String','Mouse');


        else
            go_button=uicontrol('Style','Pushbutton',...
                'Position',[.27 .05 .15 .15 ],...
                'Units','normalized',...
                'Callback','welcome;done;cluticut(4);',...
                'String','Go');
            ticut_info=uicontrol('Style','Pushbutton',...
                'Position',[.49 .05 .15 .15 ],...
                'Units','normalized',...
                'Callback','clinfo(12);',...
                'String','Info');
            mouse_button=uicontrol('Style','Pushbutton',...
                'Position',[.06 .05 .15 .15 ],...
                'Units','normalized',...
                'Callback','cltiplot(2);[tmp2,tmp1]=timeselect(1);cluticut(5);cltiplot(3);',...
                'String','Mouse');



        end

        if var1==1
            txt1 = text(...
                'Color',[0 0 0 ],...
                'EraseMode','normal',...
                'Position',[0. 0.65 0 ],...
                'Rotation',0 ,...
                'FontSize',fontsz.m ,...
                'FontWeight','bold' ,...
                'String','Starttime: ');

            txt2 = text(...
                'Color',[0 0 0 ],...
                'EraseMode','normal',...
                'Position',[0. 0.40 0 ],...
                'Rotation',0 ,...
                'FontSize',fontsz.m ,...
                'FontWeight','bold' ,...
                'String','Endtime :');



        elseif var1==2
            txt1 = text(...
                'Color',[0 0 0 ],...
                'EraseMode','normal',...
                'Position',[0. 0.65 0 ],...
                'Rotation',0 ,...
                'FontSize',fontsz.m ,...
                'FontWeight','bold' ,...
                'String','Minimum Timedifference: ');

            txt2 = text(...
                'Color',[0 0 0 ],...
                'EraseMode','normal',...
                'Position',[0. 0.45 0 ],...
                'Rotation',0 ,...
                'FontSize',fontsz.m ,...
                'FontWeight','bold' ,...
                'String','Maximum Timedifference:');
            tmp3=num2str(ttcat(1,3));
            txt3 =text(...
                'Color',[0 0 0 ],...
                'EraseMode','normal',...
                'Position',[0. 0.25 0 ],...
                'Rotation',0 ,...
                'FontSize',fontsz.m ,...
                'FontWeight','bold' ,...
                'String',['Starttime:        ',tmp3]);

        end
        set(gcf,'visible','on')

    elseif var1==3
        figure_w_normalized_uicontrolunits(clu);
        if isempty(newclcat)  &&  isempty(backcat)   %no selection before
            backequi=equi;
            backbgevent=bgevent;
        end
        tt=find(original(bg(equi(:,10)),3)>=tmp2 & original(bg(equi(:,10)),3)<=tmp1);
        equi=equi(tt,:);
        bgevent=bgevent(tt,:);

        set(equi_button,'value',1)
        st1=get(equi_button,'Callback');
        eval(st1);
        pause(2);
        tmp=equi(:,10)';
        tmpcat=clust(:,tmp);
        newclcat=original(tmpcat(find(clust(:,tmp))),:);
        plot1_h=[];plot2_h=[];
        cluoverl(7);

        strib=[' Polygon of  ' file1];
        hold on
        title(strib,'FontWeight','bold',...
            'FontSize',fontsz.l,'Color','r')


    elseif var1==4
        figure_w_normalized_uicontrolunits(clu1);
        clsel=1;
        if isempty(tt1cat)
            tt1cat=ttcat;
        end
        tt=find(tmeqtime>=tmp2 & tmeqtime<=tmp1);
        ttcat=ttcat(tt,:);
        cluoverl(8);
        strib=[' Polygon of  ' file1 ' #' num2str(new(10))];
        hold on
        title(strib,'FontWeight','bold',...
            'FontSize',fontsz.l,'Color','r')
    elseif var1==5
        figure_w_normalized_uicontrolunits(clu1);
        clsel=1;
        if isempty(tt1cat)
            tt1cat=ttcat;
        end
        tt=find(ttcat(:,3)>=tmp2 & ttcat(:,3)<=tmp1);
        ttcat=ttcat(tt,:);
        cluoverl(8);
        strib=[' Polygon of  ' file1 ' #' num2str(new(10))];
        hold on
        title(strib,'FontWeight','bold',...
            'FontSize',fontsz.l,'Color','r')


    end

