function mycat=cpara(option, mycat)
    % cpara select params in cluster environment
    %    Alexander Allmann
    % mycat=cpara(option, mycat)
    %
    
    persistent tmp1 tmp2 tmp3 tmp4 tmp5 tmp6 tmp7 tmp8 tmp9 tmp10
    
    report_this_filefun(mfilename('fullpath'));
    
    if option==1
        
        % default values
        tmp1=min(mycat.Longitude);       %longitude
        tmp2=max(mycat.Longitude);
        tmp3=min(mycat.Latitude);       %latitude
        tmp4=max(mycat.Latitude);
        tmp5=min(mycat.Date);       %time
        tmp6=max(mycat.Date);
        tmp7=min(mycat.Magnitude);       %magnitude
        tmp8=max(mycat.Magnitude);
        tmp9=min(mycat.Depth);       %depth
        tmp10=max(mycat.Depth);
        
        %make the interface
        figure_w_normalized_uicontrolunits(...
            'units','pixel','pos',[300 200 400 500],...
            'name','Select Parameters',...
            'NumberTitle','off',...
            'visible','off',...
            ...
            'NextPlot','new');
        axis off
        
        
        inp1=uicontrol('Style','edit','Position',[.47 .80 .22 .06],...
            'Units','normalized','String',num2str(tmp7),...
            'Callback','tmp7=str2double(inp1.String); inp1.String=num2str(tmp7))');
        
        inp2=uicontrol('Style','edit','Position',[.72 .80 .22 .06],...
            'Units','normalized','String',num2str(tmp8),...
            'Callback','tmp8=str2double(inp2.String); inp2.String=num2str(tmp8);');
        
        inp3=uicontrol('Style','edit','Position',[.47 .65 .22 .06],...
            'Units','normalized','String',num2str(tmp5),...
            'Callback','tmp5=str2double(inp3.String); inp3.String=num2str(tmp5);');
        
        inp4=uicontrol('Style','edit','Position',[.72 .65 .22 .06],...
            'Units','normalized','String',num2str(tmp6),...
            'Callback','tmp6=str2double(inp4.String); inp4.String=num2str(tmp6);');
        
        inp5=uicontrol('Style','edit','Position',[.47 .50 .22 .06],...
            'Units','normalized','String',num2str(tmp9),...
            'Callback','tmp9=str2double(inp5.String); inp5.String=num2str(tmp9);');
        
        inp6=uicontrol('Style','edit','Position',[.72 .50 .22 .06],...
            'Units','normalized','String',num2str(tmp10),...
            'Callback','tmp10=str2double(inp6.String); inp6.String=num2str(tmp10);');
        
        inp7=uicontrol('Style','edit','Position',[.47 .35 .22 .06],...
            'Units','normalized','String',num2str(tmp1),...
            'Callback','tmp1=str2double(inp7.String); inp7.String=num2str(tmp1);');
        
        inp8=uicontrol('Style','edit','Position',[.72 .35 .22 .06],...
            'Units','normalized','String',num2str(tmp2),...
            'Callback','tmp2=str2double(inp8.String); inp8.String=num2str(tmp2);');
        
        inp9=uicontrol('Style','edit','Position',[.47 .20 .22 .06],...
            'Units','normalized','String',num2str(tmp3),...
            'Callback','tmp3=str2double(inp9.String); inp9.String=num2str(tmp3);');
        
        inp10=uicontrol('Style','edit','Position',[.72 .2 .22 .06],...
            'Units','normalized','String',num2str(tmp4),...
            'Callback','tmp4=str2double(inp10.String); inp10.String=num2str(tmp4);');
        
        
        txt1= text(...
            'Color',[1 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.45 .99 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.l ,...
            'FontWeight','bold' ,...
            'String',' Minimum');
        
        
        txt2 = text(...
            'Color',[0 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.75 .99 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.l ,...
            'FontWeight','bold' ,...
            'String',' Maximum ');
        
        txt3 = text(...
            'Color',[0 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.0 0.88 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.xl ,...
            'FontWeight','bold' ,...
            'String','Magnitude: ');
        
        txt4 = text(...
            'Color',[0 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.0 0.70 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.xl ,...
            'FontWeight','bold' ,...
            'String','Time: ');
        txt5 = text(...
            'Color',[0 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.0 0.51 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.xl ,...
            'FontWeight','bold' ,...
            'String','Depth: ');
        txt6 = text(...
            'Color',[0 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.0 0.33 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.xl ,...
            'FontWeight','bold' ,...
            'String','Longitude: ');
        txt7 = text(...
            'Color',[0 0 0 ],...
            'EraseMode','normal',...
            'Position',[0.0 0.15 0 ],...
            'Rotation',0 ,...
            'FontSize',ZmapGlobal.Data.fontsz.xl ,...
            'FontWeight','bold' ,...
            'String','Latitude: ');
        
        close_button=uicontrol('Style','Pushbutton',...
            'Position',[.75 .02 .20 .10 ],...
            'Units','normalized','Callback','close;zmap_message_center.set_info('' '','' '');done','String','cancel');
        
        go_button=uicontrol('Style','Pushbutton',...
            'Position',[.45 .02 .20 .10 ],...
            'Units','normalized',...
            'Callback','close,think, ZG.newccat=cpara(''use_existing'',ZG.newccat);csubcat;',...
            'String','Go');
        
        info_button=uicontrol('Style','Pushbutton',...
            'Position',[.15 .02 .20 .10 ],...
            'Units','normalized',...
            'Callback','clinfo(15);',...
            'String','Info');
        
        
        set(gcf,'visible','on');
        
        
    elseif option=='use_existing'
        
        tmp11=mycat.Longitude>=tmp1 & mycat.Longitude<=tmp2 &...
            mycat.Latitude>=tmp3 & mycat.Latitude<=tmp4 &...
            mycat.Date>=tmp5 & mycat.Date<=tmp6 &...
            mycat.Magnitude>=tmp7 & mycat.Magnitude<=tmp8 &...
            mycat.Depth>=tmp9 & mycat.Depth<=tmp10;
        mycat=mycat.subset(tmp11);
        
    end
