%  This scriptfile ask for several input parameters that can be setup
%  at the beginning of each session. The default values are the
%  values Raesenberg used in this program
%  Alexander Allmann
% Last modification 8/95
report_this_filefun(mfilename('fullpath'));

global faults coastline main mainfault name
global newcat a hoda
global taumin taumax xmeff xk rfact P err derr
%routine works on newcat
%
newcat=a;
if isempty(newcat)
    newcat=a;
end


%  default values
think
taumin = 1;
taumax = 10;
P = 0.95;
xk = 0.5;
xmeff = 1.5;
rfact = 10;
err=1.5;
derr=2;

% check if catalog has hour and minute saved
%

[m,n] = size(newcat);
if n < 9 
    errdisp = ...
        ['The catalog does not   '
        'contain hour and minute'
        'data. Please reload the'
        'catalog                '];
    welcome('Error!  Alert!',errdisp)
    warndlg(errdisp)
    done;return
end


%if  max(a(:,3)) > 100;

% errdisp = ...
%['Declustering requieres  '
%'years in two digits     '
%'catalog  corrected      '
%'by subtracting 1900     ']

%welcome('Error!  Alert!',errdisp)
%warndlg(errdisp)
%a(:,3) = a(:,3)-1900; newt2 = a; newcat = a;
%end


% make the interface
%
figure_w_normalized_uicontrolunits(...
    'Units','pixel','pos',[wex wey 380 500 ],...
    'Name','Declustering Input Parameters',...
    'visible','off',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'NextPlot','new');
axis off
if term == 1; whitebg(gcf,[1 1 1 ]);end


inp1=uicontrol('Style','edit','Position',[.70 .84 .22 .05],...
    'Units','normalized','String',num2str(taumin),...
    'Callback','taumin=str2double(get(inp1,''String'')); set(inp1,''String'',num2str(taumin))');

inp2=uicontrol('Style','edit','Position',[.70 .74 .22 .05],...
    'Units','normalized','String',num2str(taumax),...
    'Callback','taumax=str2double(get(inp2,''String'')); set(inp2,''String'',num2str(taumax));');

inp3=uicontrol('Style','edit','Position',[.70 .64 .22 .05],...
    'Units','normalized','String',num2str(P),...
    'Callback','P=str2double(get(inp3,''String'')); set(inp3,''String'',num2str(P));');


inp4=uicontrol('Style','edit','Position',[.70 .54 .22 .05],...
    'Units','normalized','String',num2str(xk),...
    'Callback','xk=str2double(get(inp4,''String'')); set(inp4,''String'',num2str(xk));');

inp5=uicontrol('Style','edit','Position',[.70 .44 .22 .05],...
    'Units','normalized','String',num2str(xmeff),...
    'Callback','xmeff=str2double(get(inp5,''String'')); set(inp5,''String'',num2str(xmeff));');

inp6=uicontrol('Style','edit','Position',[.70 .34 .22 .05],...
    'Units','normalized','String',num2str(rfact),...
    'Callback','rfact=str2double(get(inp6,''String'')); set(inp6,''String'',num2str(rfact));');

inp7=uicontrol('Style','edit','Position',[.70 .24 .22 .05],...
    'Units','normalized','String',num2str(err),...
    'Callback','err=str2double(get(inp7,''String'')); set(inp7,''String'',num2str(err));');

inp8=uicontrol('Style','edit','Position',[.70 .14 .22 .05],...
    'Units','normalized','String',num2str(derr),...
    'Callback','derr=str2double(get(inp8,''String'')); set(inp8,''String'',num2str(derr));');


close_button=uicontrol('Style','Pushbutton',...
    'Position',[.85 .02 .16 .08 ],...
    'Units','normalized','Callback','close,done','String','cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.3 .02 .20 .08 ],...
    'Units','normalized',...
    'Callback','taumin=str2num(get(inp1,''String''));taumax=str2num(get(inp2,''String''));P=str2num(get(inp3,''String''));xk=str2num(get(inp4,''String''));xmeff=str2num(get(inp5,''String''));rfact=str2num(get(inp6,''String''));err=str2num(get(inp7,''String''));derr=str2num(get(inp8,''String''));close;think;declus;',...
    'String','Go Matlab');

go_button2=uicontrol('Style','Pushbutton',...
    'Position',[.55 .02 .20 .08 ],...
    'Units','normalized',...
    'Callback','taumin=str2num(get(inp1,''String''));taumax=str2num(get(inp2,''String''));P=str2num(get(inp3,''String''));xk=str2num(get(inp4,''String''));xmeff=str2num(get(inp5,''String''));rfact=str2num(get(inp6,''String''));err=str2num(get(inp7,''String''));derr=str2num(get(inp8,''String''));close;think;save_declus;',...
    'String','Go FORTRAN');


info_button=uicontrol('Style','Pushbutton',...
    'Position',[.05 .02 .15 .08 ],...
    'Units','normalized',...
    'Callback','clinfo(9); web([''file:'' hodi ''/zmapwww/chap7.htm#996752''])',...
    'String','Info');


txt3 = text(...
    'Color',[1 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.05 1.00 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','Declustering Parameters: ');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.92 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','Taumin: ');
txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.80 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','Taumax :');
txt4 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.68 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','P1 : ');

txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.56 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','XK : ');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.43 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','XMEFF : ');

txt7 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.30 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','RFACT : ');

txt8 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.18 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','Epicenter-Error :');

txt9 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.07 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold' ,...
    'FontSize',fontsz.m ,...
    'String','Depth-Error : ');

set(gcf,'visible','on')
watchoff
done

%clear txt1 txt2 txt3 txt4 txt5 txt6 txt7 inp1 inp2 inp3 inp4 inp5 inp6 inp7



