function inpudenew()
    %  This scriptfile ask for several input parameters that can be setup
    %  at the beginning of each session. The default values are the
    %  values Raesenberg used in this program
    %  Alexander Allmann
    
    % modified Celso Reyes 2017
    report_this_filefun(mfilename('fullpath'));
    
    global faults coastline main mainfault name
    global newcat a wex wey
    global taumin taumax xmeff xk rfact P err derr
    %routine works on newcat
    %
    newcat=a;
    if isempty(newcat)
        newcat=a;
    end
    
    
    %  default values
    think
    taumin = 1;
    taumax = 10;
    P = 0.95;
    xk = 0.5;
    xmeff = 1.5;
    rfact = 10;
    err=1.5;
    derr=2;
    
    % check if catalog has hour and minute saved
    %
    
    % make the interface
    %
    figure_w_normalized_uicontrolunits(...
        'Units','pixel','pos',[wex wey 250 380 ],...
        'Name','Declustering Input Parameters',...
        'visible','off',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'NextPlot','new');
    axis off
    
    
    help_taumin='look ahead time for not clustered events';
    help_taumax= 'maximum look ahead time for clustered events';
    help_P= 'Confidence level : observing the next event in the sequence';
    help_xk = 'factor used in xmeff';
    help_rfact='factor for interaction radius for dependent events';
    help_xmeff = '"effective" lower magnitude cutoff for catalog, during clusters, it is xmeff^{xk*cmag1}';
    
    
    edit_taumin = uicontrol('Style','edit','Position',[.65 .69 .30 .06],...
        'Units','normalized','String',num2str(taumin),...
        'TooltipString',help_taumin,...
        'Callback',@set_numeric);
    
    edit_taumax = uicontrol('Style','edit','Position',[.65 .61 .30 .06],...
        'Units','normalized','String',num2str(taumax),...
        'TooltipString',help_taumax,...
        'Callback',@set_numeric);
    
    edit_P = uicontrol('Style','edit','Position',[.65 .53 .30 .06],...
        'Units','normalized','String',num2str(P),...
        'TooltipString',help_P,...
        'Callback',@set_numeric);
    
    
    edit_xk = uicontrol('Style','edit','Position',[.65 .45 .3 .06],...
        'Units','normalized','String',num2str(xk),...
        'TooltipString',help_xk,...
        'Callback',@set_numeric);
    
    edit_xmeff = uicontrol('Style','edit','Position',[.65 .37 .3 .06],...
        'Units','normalized','String',num2str(xmeff),...
        'TooltipString',help_xmeff,...
        'Callback',@set_numeric);
    
    edit_rfact = uicontrol('Style','edit','Position',[.65 .29 .3 .06],...
        'Units','normalized','String',num2str(rfact),...
        'TooltipString',help_rfact,...
        'Callback',@set_numeric);
    
    edit_err = uicontrol('Style','edit','Position',[.65 .21 .3 .06],...
        'Units','normalized','String',num2str(err),...
        'Callback',@set_numeric);
    
    edit_derr = uicontrol('Style','edit','Position',[.65 .13 .3 .06],...
        'Units','normalized','String',num2str(derr),...
        'Callback',@set_numeric);
    
    
    close_button=uicontrol('Style','Pushbutton',...
        'Position',[.78 .02 .21 .09 ],...
        'Units','normalized','Callback','close,done','String','cancel');
    
    go_button=uicontrol('Style','Pushbutton',...
        'Position',[.505 .02 .28 .09 ],...
        'Units','normalized',...
        'Callback',@(s,e)go_matlab,...
        'String','Go MatLab');
    
    %{
    go_button2=uicontrol('Style','Pushbutton',...
        'Position',[.205 .02 .30 .09 ],...
        'Units','normalized',...
        'Callback','taumin=str2num(get(inp1,''String''));taumax=str2num(get(inp2,''String''));P=str2num(get(inp3,''String''));xk=str2num(get(inp4,''String''));xmeff=str2num(get(inp5,''String''));rfact=str2num(get(inp6,''String''));err=str2num(get(inp7,''String''));derr=str2num(get(inp8,''String''));close;think;save_declus;',...
        'String','Go FORTRAN');
    %}
    
    info_button=uicontrol('Style','Pushbutton',...
        'Position',[.01 .02 .20 .09 ],...
        'Units','normalized',...
        'Callback','clinfo(9); web([''file:'' hodi ''/zmapwww/chap7.htm#996752''])',...
        'String','Info');
    
    
    uicontrol('Style','text',...
        'ForegroundColor',[0 0 .3 ],...
        'Position',[0.1 .9 .8 .1 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.l ,...
        'HorizontalAlignment','Center',...
        'String','Declustering Parameters:');
    
    text(...
        'Position',[0.5 0.95 0 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','Center',...
        'String','(mouseover field for tool-tip help)');
    
    uicontrol('Style','text',...
        'Position',[0.1 0.69 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','Taumin: ');
    uicontrol('Style','text',...
        'Position',[0.1 0.61 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','Taumax :');
    uicontrol('Style','text',...
        'Position',[0.1 0.53 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','P1 : ');
    
    uicontrol('Style','text',...
        'Position',[0.1 0.45 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','XK : ');
    
    uicontrol('Style','text',...
        'Position',[0.1 0.37 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','XMEFF : ');
    
    uicontrol('Style','text',...
        'Position',[0.1 0.29 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','RFACT : ');
    
    uicontrol('Style','text',...
        'Position',[0.1 0.21 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','Epicenter-Error :');
    
    uicontrol('Style','text',...
        'Position',[0.1 0.13 .6 .06 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'HorizontalAlignment','left',...
        'String','Depth-Error : ');
    
    set(gcf,'visible','on')
    watchoff
    done
    
    function set_numeric(s,~)
        s.Value = num2str(s.String);
    end
    
    function go_matlab()
        taumin=edit_taumin.Value;
        taumax=edit_taumax.Value;
        P=edit_P.Value;
        xk=edit_xk.Value;
        xmeff=edit_xmeff.Value;
        rfact=edit_rfact.Value;
        err=edit_err.Value;
        derr=edit_derr.Value;
        close;
        think;
        declus()
        %declus(taumin,taumax,xk,xmeff,P,rfact,err,derr);
    end
end


