#!/bin/csh
  unalias mv
  foreach j  (*.m)
        set nam  = `echo $j | awk -F. '{ printf("%s", $1) }'`
        echo $nam
        cat $nam.m |sed -e "s/'back'/'normal'/g"  > tmp
        mv tmp $j
end

