function [zmg, gpc] = autogrid(catalog, doplot, plotOnMap)
    % automatically define grid parameters based on catalog
    % returns a ZmapGrid, 
    % zmg, gparam = autogrid(catalog, doplot, plotOnMap)
    
    
    [N,XEDGES,YEDGES] = histcounts2(...
        catalog.Longitude,...
        catalog.Latitude,...
        'BinMethod','fd');
    
    zmg=ZmapGrid('autogrid',XEDGES(1:end-1)-diff(XEDGES(1:2))/2,...
        YEDGES(1:end-1)-diff(YEDGES(1:2))/2,'deg');
    
    gpc=struct('dx',diff(XEDGES(1:2))/2,...
        'dy',diff(YEDGES(1:2))/2,...
        'dz',[],...
        'dx_units','deg',...
        'dy_units','deg',...
        'dz_units','km',...
        'GridEntireArea',true,...
        'SaveGrid',false,...
        'LoadGrid',false,...
        'CreateGrid',false); %should be done in conj. with GridParameterChoice
    
    if exist('doplot','var') && doplot
        figure('Name','Automatic Grid');
        histogram2(catalog.Longitude,catalog.Latitude,XEDGES,YEDGES);
        title('Event distribution')
        xlabel('Longitude')
        ylabel('Latitude')
        zlabel('# events')
    end
    if exist('plotOnMap','var') && plotOnMap
        zmg.plot(MainInteractiveMap.mainAxes);
    end
end