function newcircleselect_sample()
    % replace the circle dialog with something like this?
    f=figure('Name','circle selection',...
        'menubar','none','numbertitle','off',...
        'Units','points',...
        'position',[150 150 350 400]);
    
    % divide figure into major tab groups
    topTabs = uitabgroup(f,'position',[0 0.55 1 0.4]);
    botTabs = uitabgroup(f,'position',[0 0.05 1 0.4]);
    
    % select center point
    mantab = uitab(topTabs,'title','Manual',...
        'tooltipstring','manually specify the center point');
    
    mstab = uitab(topTabs,'title','Mouse Select',...
        'tooltipstring', 'select the center point using the mouse');
    
    mctab = uitab(topTabs,'title','Map Center',...
        'tooltipstring', 'use the current figure''s center as the circle center');
    
    
    % select radius definition
    max_rad = uitab(botTabs,'title','Max. Radius',...
        'tooltipstring','select all events within radius');
    
    
    n_events = uitab(botTabs,'title','# Events',...
        'tooltipstring', 'select N closest events');
    
    both = uitab(botTabs,'title','  Both  ',...
        'tooltipstring', 'select N closest events (out to specified radius)');
    
    
    % center point definitions
    % MANUAL tab
    edx = uicontrol(mantab,'Style','edit',...
        'tooltipstring','enter Longitude',...
        'String','LON (x)',...
        'Value',0,...
        'units','normalized',...
        'callback',@(src,~)set(src,'Value',str2double(src.String),...
                                'String',get(findobj(src.Parent,'Tag','rounderSlider'),'value')),...
        'position',[.2 .6 .3 .3]);
    edy = uicontrol(mantab,'Style','edit',...
        'tooltipstring','enter Latitude',...
        'String','LAT (y)',...
        'units','normalized',...
        'position',[.5 .6 .3 .3]);
    
    % MOUSE tab
    edx = uicontrol(mstab,'Style','edit',...
        'tooltipstring','enter Longitude',...
        'String','LON (x)',...
        'units','normalized',...
        'Tag','lon',...
        'position',[.2 .6 .3 .3]);
    edy = uicontrol(mstab,'Style','edit',...
        'tooltipstring','enter Latitude',...
        'String','LAT (y)',...
        'units','normalized',...
        'Tag','lat',...
        'position',[.5 .6 .3 .3]);
    slval = uicontrol(mstab,'Style','edit',...
        'units','normalized',...
        'Tag','rounderEdit',...
        'position',[.65 .1 .2 .3],...
        ...'Enable','off',...
        'callback',@slider_cb);
    decplace = uicontrol(mstab,'Style','slider',...
        'tooltipstring','round to N decimal places (-2=100''s, 2=0.01)',...
        'units','normalized',...
        'position',[.2 .1 .4 .3],...
        'Value',1,...
        'Tag','rounderSlider',...
        'Min',-2','Max',4,'SliderStep',[1 4]/7,...
        'callback',@slider_cb); % also set to
    slval.String = num2str(decplace.Value);
    
    % debugstop
    % max radius tab items
    % invert selection checkbox (off)
    %
    
    disp('debug stop opportunity')
end

function slider_cb(src,~)
    
    switch src.Style
        case 'slider'
            src.Value = round(src.Value);
            src.String = num2str(src.Value);
            set(findobj(src.Parent','Tag','rounderEdit'),...
                'Value',src.Value,...
                'String',src.String);
        case 'edit'
            sld=findobj(src.Parent','Tag','rounderSlider');
            tmp = round(str2double(src.String));
            if (tmp > sld.Max || tmp < sld.Min)
                beep;
                ZmapMessageCenter.set_error('rounding slider','rounding out of range');
                src.String = num2str(src.Value);
                return
            end
            src.Value = tmp;
            src.String = num2str(tmp);
            set(sld,...
                'Value',tmp,...
                'String',src.String);
    end
   
end
