f=figure('Name','circle selection',...
    'menubar','none','numbertitle','off',...
    'Units','points',...
    'position',[150 150 350 400]);

% divide figure into major tab groups
topTabs = uitabgroup(f,'position',[0 0.55 1 0.4]);
botTabs = uitabgroup(f,'position',[0 0.05 1 0.4]);

% select center point
mantab = uitab(topTabs,'title','Manual',...
    'tooltipstring','manually specify the center point');

mstab = uitab(topTabs,'title','Mouse Select',...
    'tooltipstring', 'select the center point using the mouse');

mctab = uitab(topTabs,'title','Map Center',...
    'tooltipstring', 'use the current figure''s center as the circle center');


% select radius definition
max_rad = uitab(botTabs,'title','Max. Radius',...
    'tooltipstring','select all events within radius');


n_events = uitab(botTabs,'title','# Events',...
    'tooltipstring', 'select N closest events');

both = uitab(botTabs,'title','  Both  ',...
    'tooltipstring', 'select N closest events (out to specified radius)');


% center point definitions
% MANUAL tab
edx = uicontrol(mantab,'Style','edit',...
    'tooltipstring','enter Longitude',...
    'String','LON (x)',...
    'units','normalized',...
    'position',[.2 .6 .3 .3]);
edy = uicontrol(mantab,'Style','edit',...
    'tooltipstring','enter Latitude',...
    'String','LAT (y)',...
    'units','normalized',...
    'position',[.5 .6 .3 .3]);

% MOUSE tab
edx = uicontrol(mstab,'Style','edit',...
    'tooltipstring','enter Longitude',...
    'String','LON (x)',...
    'units','normalized',...
    'position',[.2 .6 .3 .3]);
edy = uicontrol(mstab,'Style','edit',...
    'tooltipstring','enter Latitude',...
    'String','LAT (y)',...
    'units','normalized',...
    'position',[.5 .6 .3 .3]);
slval = uicontrol(mstab,'Style','edit',...
    'units','normalized',...
    'position',[.65 .1 .2 .3],'Enable','off');
decplace = uicontrol(mstab,'Style','slider',...
    'tooltipstring','round to N decimal places (-2=100''s, 2=0.01)',...
    'units','normalized',...
    'position',[.2 .1 .4 .3],...
    'Value',1,...
    'Min',-2','Max',4,'SliderStep',[1 4]/7,...
    'callback',@(src,~) set(slval,'Value',round(src.Value),'String',num2str(round(src.Value)))); % also set to 
slval.String = num2str(decplace.Value);


% max radius tab items
% invert selection checkbox (off)
% 