classdef XSectionManager < handle
    % XSECTIONMANAGER manage cross sections
    % 
    %   manages the XSection class, making them available to all
    %
    
    properties
        xsections; % contains XSection 
        xscats; % ZmapXsectionCatalogs corresponding to each cross section
        xscatinfo %stores details about the last catalog used to get cross section, avoids 
        
    end
    
    properties(Dependent)
        names
    end
    
    methods
        function obj = XSectionManager()
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
            
            obj.xsections=containers.Map();
            obj.xscats=containers.Map();
            obj.xscatinfo=containers.Map();
        end
        
        function tf=isempty(obj)
            tf=isempty(obj.xsections);
        end
            
        function s = get.names(obj)
            s=obj.xsections.keys;
        end
        
        function gr = grid(obj,name, x_km, zs_km)
            gr = obj.xsections(name).getGrid(x_km, zs_km);
        end
        
        function disp(obj)
            disp(obj.xsections)
        end
        
        function xs = choose(obj)
            disp('choose a cross section')
        end
        function c = catalog(obj, name)
            c=obj.xscats(name);
        end
            
        function change_color(obj,key, color)
            
        end
           
        
        function xsec_remove(obj, key)
            % XSEC_REMOVE completely removes cross section from object
            obj.xsections.remove(key);
            obj.xscats.remove(key);
            obj.xscatinfo.remove(key);
        end
        
        function xsec_add(obj, key, xsec, catalog, catinfo)
            %XSEC_ADD add/replace cross section
            obj.xsections(key)=xsec;
            % add catalog generated by the cross section (ignoring shape)
            obj.xscats(key)= xsec.project(catalog);
            % add the information about the catalog used
            obj.xscatinfo(key)=catinfo;
            
        end
        
    end
end

