
report_this_filefun(mfilename('fullpath'));
switch(ac3)

case 'new'


   to1 = figure_w_normalized_uicontrolunits( ...
        'Name','Lambert Map',...
        'NumberTitle','off', ...
        'backingstore','on',...
        'NextPlot','add', ...
        'Visible','on', ...
        'Position',[ (fipo(3:4) - [600 500]) ZmapGlobal.Data.map_len]);

matdraw


return

  labelList=[' flat | interp | faceted '];
  labelPos = [0.9 0.93 0.10 0.05];
   hndl3=uicontrol(...
      'Style','popup',...
      'Units','normalized',...
      'Position',labelPos,...
      'Value',1,...
      'String',labelList,...
      'BackgroundColor',[0.7 0.7 0.7]',...
      'Callback','ac3 = ''eva1''; overmap');


 labelList=[' Volcanoes on  | off '];
  labelPos = [0.9 0.75 0.10 0.05];
   hndl2=uicontrol(...
      'Style','popup',...
      'Units','normalized',...
      'Position',labelPos,...
      'Value',1,...
      'String',labelList,...
      'BackgroundColor',[0.7 0.7 0.7]',...
      'Callback','ac3 = ''eva2''; overmap');


  uicontrol('Units','normal',...
          'Position',[.0 .0 .08 .04],'String','zoom ',...
           'Callback','zoomrb')



 labelList=[' EQ (dot) | EQ (o) | No EQ '];
  labelPos = [0.9 0.65 0.10 0.05];
   hndl4=uicontrol(...
      'Style','popup',...
      'Units','normalized',...
      'Position',labelPos,...
      'Value',1,...
      'String',labelList,...
      'BackgroundColor',[0.7 0.7 0.7]',...
      'Callback','ac3 = ''eva4''; overmap');


 labelList=[' Faults  | No Faults '];
  labelPos = [0.9 0.55 0.10 0.05];
   hndl5=uicontrol(...
      'Style','popup',...
      'Units','normalized',...
      'Position',labelPos,...
      'Value',1,...
      'String',labelList,...
      'BackgroundColor',[0.7 0.7 0.7]',...
      'Callback','ac3 = ''eva5''; overmap');


 labelList=[' Main  | No Main '];
  labelPos = [0.9 0.35 0.10 0.05];
   hndl7=uicontrol(...
      'Style','popup',...
      'Units','normalized',...
      'Position',labelPos,...
      'Value',1,...
      'String',labelList,...
      'BackgroundColor',[0.7 0.7 0.7]',...
      'Callback','ac3 = ''eva7''; overmap');





case 'eva1'
     in3 =get(hndl3,'Value');
     if in3 == 1 ; shading flat ; end
     if in3 == 2 ; shading interp ; end
     if in3 == 3 ; shading faceted ; end

case 'eva2'
     in3 =get(hndl2,'Value');
    if in3 == 1
       plovo = plot(vo.Longitude,vo.Latitude,'^r');
       set(plovo,'LineWidth',1.5,'MarkerSize',8,...
      'MarkerFaceColor','w','MarkerEdgeColor','r');
    end
    if in3 == 2 ; delete(plovo);  end

case 'eva4'

     in3 =get(hndl4,'Value');
     if in3 == 1 ; ploe = plot(ZG.a.Longitude,ZG.a.Latitude,'.r','MarkerSize',1) ; end
     if in3 == 2 ; ploe = plot(ZG.a.Longitude,ZG.a.Latitude,'or','MarkerSize',2) ; end
     if in3 == 3 ; delete(ploe);  end

case 'eva5'
     in3 =get(hndl5,'Value');
     if in3 == 1 ;  end
     if in3 == 2 ; delete(plof) ; end

case 'eva7'
     in3 =get(hndl7,'Value');
     if in3 == 1 
        epimax2 = m_line(ZG.maepi.Longitude,ZG.maepi.Latitude);
        set(epimax2,'LineWidth',1.5,'MarkerSize',12,'Marker','h',...
       'MarkerFaceColor','y','MarkerEdgeColor','k')
      end

        if in3 == 2 ; delete(epimax2);  end


end
