function [out, eMethod] = declus_inp(catalog, varargin)
    % declusters a catalog using window technique by Gardiner & Knopoff
    % ---------------------------------------------------------------
    % This script asks for input parameters that need to be setup
    % at the beginning of declustering a catalog using the windowing
    % technique by Gardner & Knopoff.
    %
    % J. Woessner, woessner@seismo.ifg.ethz.ch
    % updated: 02.09.02
    
    report_this_filefun();
    
    global mCatalog
    
    storedcat=catalog; % Keep original catalog for resetting in Seismicity map
    
    mCatalog=catalog; % Script works on mCatalog
    
    methoddescriptions = string(enumeration('DeclusterWindowingMethods'));
    eMethod = DeclusterWindowingMethods.GardinerKnopoff1974;  % default declusting methods
    idx = listdlg('ListString', string(enumeration('DeclusterWindowingMethods')),...
        'SelectionMode', 'single', ...
        'PromptString', 'Choose window size',...
        'InitialValue', double(DeclusterWindowingMethods.GardinerKnopoff1974));
    eMethod = DeclusterWindowingMethods(idx);
    if isempty(eMethod)
        % act as if we declustered, but found no clusters
        disp('Declustering cancelled')
        out = struct();
        out.declusteredCatalog = catalog;
        out.aftershockCatalog = catalog.subset([]);
        out.allClusterIdx = false(catalog.Count,1);
        out.aftershockClusterIdx = out.allClusterIdx;
        out.mainshockClusterIdx = out.allClusterIdx;
    else
        out = declus_wintec(catalog, eMethod);
    end
        
    
    return
    % Make the interface
    %
    bas_fig=figure(...
        'Units','pixel','pos',[ZmapGlobal.Data.welcome_pos 400 300 ],...
        'Name','Declustering - Windowing approach',...
        'NumberTitle','off',...
        'NextPlot','new');
    axis off
    
    
    %%%%% Documentation for Matlab window
    titlestr1 = 'Help on declustering using Gardner and Knopoff approach';
    
    infostr1 = [' The declustering method by Gardner & Knopoff (1974) uses predefined'...
        ' windows in space and time to identify dependent and independent seismicity.'...
        ' For comparison, three window suggestions in space and time from different'...
        ' authors (Gardner & Knopoff (1974), Gruenthal (pers. comm.), Uhrhammer (1986))'...
        ' are implemented. Use the PLOT button to have a glance on the window sizes. Choose the window'...
        ' using the popup menu. Use the GO button to start the declustering. As a result,'...
        ' the clusters and mainshocks are plotted in the seismicity map, a message box'...
        ' including information on the clusters pops up. Moreover, a comparison of the cluster length'...
        ' to the predefined windos and a histogram showing'...
        ' the magnitude distribution of all events in the clusters is plotted. After declustering, use the '...
        ' CREATE button to plot a seperate map of declustering. Choose appropriate values, depending on either'...
        ' the radius or the max. number of events to determine the degree. Additional help is found in the '...
        ' MATLAB help window.'];
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% Input
    uicontrol('Style','popup','Position',[.20 .6 .5 .1],...
        'Units','normalized',...
        'String',methoddescriptions,...
        'Value', find(methoddescriptions==string(eMethod)),...
        'Callback',@cb_setmethod);
    
    % Buttons
    uicontrol('Style','Pushbutton','String','Plot',...
        'Position',[.3 .35 .2 .1 ],...
        'Units','normalized','Callback',@(~,~)plot_cluster_win());
    
    uicontrol('Style','Pushbutton','String','Create',... % do the declustering
        'Position',[.3 .14 .2 .1 ],...
        'Units','normalized','Callback',@(~,~)clusterdeg(catalog));
    
    uicontrol('Style','Pushbutton','String','Exit',... % cancel button
        'Position',[.65 .02 .20 .08 ],...
        'Units','normalized',...
        'Callback',@cb_cancel);
    
    uicontrol('Style','Pushbutton','String','Go',...
        'Position',[.8 .6 .20 .095],...
        'Units','normalized',...
        'Callback',@cb_go);
    
    uicontrol('Style','Pushbutton','String','Info',...
        'Position',[.10 .02 .20 .08 ],...
        'Units','normalized',...
        'Callback',@cb_help);
    
    %% Text
    txt1 = text(...
        'Color',[1 0 0 ],...
        'Position',[0.2 1.00 0 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Declustering menu ');
    txt2 = text(...
        'Position',[0.02 0.8 0 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Choose window size:');
    txt3 = text(...
        'Position',[0.02 0.5 0 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Show space and time windows:');
    txt4 = text(...
        'Position',[0.02 0.22 0 ],...
        'FontWeight','bold' ,...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Create degree of clustering map:');
    
    function cb_go(~,~)
        close(findobj('tag','fig_win'));
        declusterstuff = declus_wintec(catalog,eMethod);
        
    end
    
    
    function cb_help(~,~)
        zmaphelp(titlestr1,infostr1);
        web(['file:' hodi '/zmapwww/declus_win/index.html'],'-browser');
    end
    
    function cb_cancel(~,~)
        close(findobj('tag','fig_win'));
        close(findobj('tag','fig_clus'));
        close(findobj('tag','fig_declus_wintec'));
        close
    end
    function cb_setmethod(src,~)
        eMethod=src.Value;
    end
end