function genbw() % autogenerated function wrapper
% Matlab script to write output from genas to a file.
% writes two files: one for results for magnitudes and below
% another for magnitudes and above.
%
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals
report_this_filefun(mfilename('fullpath'));

figure
clf ;

[tbin,zmag,zval] = find(ZBEL);           % deal with sparse matrix results
xtz = t0b + (tbin*days(ZG.bin_days));
zmag = minmg+(zmag-1)*magstep;
[xx,l] = sort(xtz);                     % sort in time
xtz = xtz(l);
zmag = zmag(l);
zval = zval(l);
tbin = tbin(l);
Z = [tbin'; xtz'; zmag'; zval'];

rect = [0.15 0.15 0.3 0.7];
axes('pos',[rect]);
set(gca,'FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','normal');

if length(Z(1,:)) > 0
    l = Z(4,:)  > 6; Z(4,l)  = Z(4,l)*0+6 ;
    l = Z(4,:)  < -6; Z(4,l)  = Z(4,l)*0-6 ;
    for i = 1:length(Z(1,:))
        if Z(4,i) > 0
            pl = plot(Z(3,i),Z(2,i),'+k');
        else
            pl = plot(Z(3,i),Z(2,i),'ok');
        end
        set(pl,'MarkerSize',abs(Z(4,i)),'LineWidth',abs(Z(4,i)/3))
        set(pl,'MarkerFaceColor','w','MarkerEdgeColor','k');

        hold on
    end
end

axis([ minmg maxmg t0b teb])


ylabel('Time (yrs)','FontWeight','normal','FontSize',ZmapGlobal.Data.fontsz.m);
xlabel('Mag <','FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','normal');
set(gca,'FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','normal',...
    'Ticklength',[0.02 0.02],'LineWidth',1.0,...
    'Box','on','SortMethod','childorder','TickDir','out')

set(gca,'Color',color_bg)


[tbin,zmag,zval] = find(ZABO);
xtz = t0b + (tbin*days(ZG.bin_days));
zmag = minmg+(zmag-1)*magstep;
[xx,l] = sort(xtz);                     % sort in time
xtz = xtz(l);
zmag = zmag(l);
zval = zval(l);
tbin = tbin(l);
Z = [tbin'; xtz'; zmag'; zval'];

rect = [0.45 0.15 0.3 0.7];
axes('pos',[rect]);
set(gca,'FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','normal',...
    'Ticklength',[0.02 0.02],'LineWidth',1.0,...
    'Box','on','SortMethod','childorder','TickDir','out')

if length(Z(1,:)) > 0
    l = Z(4,:)  > 6; Z(4,l)  = Z(4,l)*0+6 ;
    l = Z(4,:)  < -6; Z(4,l)  = Z(4,l)*0-6 ;

    for i = 1:length(Z(1,:))
        if Z(4,i) > 0
            pl = plot(Z(3,i),Z(2,i),'+k');
        else
            pl = plot(Z(3,i),Z(2,i),'ok');
        end
        hold on
        set(pl,'MarkerSize',abs(Z(4,i)),'LineWidth',abs(Z(4,i)/3))
        set(pl,'MarkerFaceColor','w','MarkerEdgeColor','k');
    end
end

axis([ minmg maxmg t0b teb])
xlabel('Mag >','FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','normal');
set(gca,'Yticklabels',[])

set(gca,'FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','normal',...
    'Ticklength',[0.02 0.02],'LineWidth',1.0,...
    'Box','on','SortMethod','childorder','TickDir','out')
%set(gca,'Color',color_bg)
set(gcf,'Color',color_fbg)

te = text(1.1,0.9,'Positive z: + ','Units','normalized','FontWeight','normal');
te = text(1.1,0.8,'Negative z: o ','Units','normalized','FontWeight','normal');



uicontrol('Units','normal',...
    'Position',[.0 .85 .08 .06],'String','Info ',...
     'callback',@callbackfun_001);



function callbackfun_001(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  infoz(1);
end
 
end
