function makegrid() % autogenerated function wrapper
    %
    %   This .m file creates a rectangular grid and calculates the
    %   cumulative number curve at each grid point. The grid is
    %   saved in the file "cumugrid.mat".
    %                        Operates on catalogue "a"
    %
    % define size of the area
    %
    % ________________________________________________________________________
    %  Please use the left mouse button or the cursor to select the lower
    %  left corner of the area of investigation. Please use the left
    %  mouse again to select the upper right corner. The calculation might take
    %  some time. This time can be reduced by using a smaller area and/or
    %  a larger grid-spacing! The amount of calculation done will be displayed
    %  in percent of the total time.
    %
    %_________________________________________________________________________
    % turned into function by Celso G Reyes 2017
    
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    report_this_filefun(mfilename('fullpath'));
    
    selgp
    
    itotal = length(newgri(:,1));
    if length(gx) < 2  ||  length(gy) < 2
        errordlg('Selection too small! (not a matrix)');
        return
    end
    
    try close(gpf); end
    try close(gh); end
    
    zmap_message_center.clear_message();;think
    %  make grid, calculate start- endtime etc.  ...
    %
    t0b = min(ZG.a.Date)  ;
    n = ZG.a.Count;
    teb = max(ZG.a.Date) ;
    tdiff = round((teb-t0b)/ZG.bin_days);
    cumu = zeros(length(t0b:days(ZG.bin_days):teb)+2);
    ncu = length(cumu);
    cumuall = zeros(ncu,length(newgri(:,1)));
    loc = zeros(3,length(newgri(:,1)));
    
    % loop over  all points
    %
    i2 = 0.;
    i1 = 0.;
    allcount = 0.;
    %
    % loop for all grid points
    wai = waitbar(0,' Please Wait ...  ');
    set(wai,'NumberTitle','off','Name','Makegrid - Percent completed');;
    drawnow
    cvg = [];
    
    for i= 1:length(newgri(:,1))
        
        x = newgri(i,1);y = newgri(i,2);
        allcount = allcount + 1.;
        i2 = i2+1;
        % calculate distance from center point and sort wrt distance
        %
        l=ZG.a.epicentralDistanceTo(x,y);
        [s,is] = sort(l);
        b = a(is(:,1),:) ;       % re-orders matrix to agree row-wise
        % take first ni points
        %
        b = b(1:ni,:);      % new data per grid point (b) is sorted in distance
        [st,ist] = sort(b);   % re-sort wrt time for cumulative count
        b = b(ist(:,3),:);
        cumu = cumu * 0;
        % time (bin) calculation
        n = b.Count;
        cumu = histogram(b(1:n,3),t0b:days(ZG.bin_days):teb);
        cumu2 = cumsum(cumu);
        %calcsimp
        %cvg = [cvg ; cv rcv];
        % end
        
        l = sort(l);
        cumuall(:,allcount) = [cumu';  x; l(ni)];
        loc(:,allcount) = [x ; y; l(ni)];
        
        waitbar(allcount/itotal)
        
    end  % for x0
    
    %
    % save data
    %
    %  set(txt1,'String', 'Saving data...')
    close(wai)
    drawnow
    %save cumugrid.mat cumuall ZG.bin_days ni dx dy gx gy tdiff t0b teb loc
    
    catsave3('makegrid');
    
    watchoff
    zmapmenu()
    return
    
    figure(mess);
    clf
    set(gca,'visible','off')
    
    te = text(0.01,0.95,'The cumulative number array \newlinehas been saved in \newlinefile cumugrid.mat \newlinePlease rename it \newlineto protect if from overwriting.');
    set(te,'FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','bold')
    
    uicontrol('Units','normal','Position',...
        [.7 .10 .2 .12],'String','Options ', 'callback',@(~,~)zmapmenu)
    
    uicontrol('Units','normal','Position',...
        [.3 .10 .2 .12],'String','Back', 'Callback',@(~,~)zmap_Message_center())
    
    return
    
    normlap2=nan(length(tmpgri(:,1)),1)
    normlap2(ll)= cvg(:,1);
    re3=reshape(normlap2,length(yvect),length(xvect));
    Prmap = re3;
    old1 = re3;
    view_bva(lab1,re3);
    

end
