function show_cro(method) % autogenerated function wrapper
    % ZMAP script show_map.m. Creates Dialog boxes for Z-map calculation
    % does the calculation and makes displays the map
    % stefan wiemer 11/94
    %
    % make dialog interface and call maxzlta
    %
    % turned into function by Celso G Reyes 2017
    error('Replaced (enveloped) by magrcro')
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    
    % Input Rubberband
    %
    report_this_filefun(mfilename('fullpath'));
    
    
    %initial values
    ZG.compare_window_dur_v3 = years(1.5);
    it = t0b +day(1);
    figure(mess);
    clf
    set(gca,'visible','off')
    set(gcf,'Units','pixel','NumberTitle','off','Name','Input Parameters');
    
    set(gcf,'pos',[ ZG.welcome_pos ZG.welx+200 ZG.wely-50])
    
    
    % creates a dialog box to input some parameters
    %
    
    inp2_field=uicontrol('Style','edit',...
        'Position',[.80 .775 .18 .15],...
        'Units','normalized','String',num2str(it),...
        'callback',@callbackfun_001);
    
    txt2 = text(...
        'Position',[0. 0.9 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input time of cut in years (e.g. 86.5):');
    
    if method == 'rub' || method == 'lta'
        
        txt3 = text(...
            'Position',[0. 0.65 0 ],...
            'FontWeight','bold',...
            'FontSize',ZmapGlobal.Data.fontsz.m ,...
            'String','Please input window length in years (e.g. 1.5):');
        inp3_field=uicontrol('Style','edit',...
            'Position',[.80 .575 .18 .15],...
            'Units','normalized','String',num2str(years(ZG.compare_window_dur)),...
            'callback',@callbackfun_002);
        
    end
    
    close_button=uicontrol('Style','Pushbutton',...
        'Position', [.60 .05 .15 .15 ],...
        'Units','normalized','Callback',@(~,~)ZmapMessageCenter(),'String','Cancel');
    
    go_button=uicontrol('Style','Pushbutton',...
        'Position',[.25 .05 .15 .15 ],...
        'Units','normalized',...
        'callback',@go_cb,...
        'String','Go');
    
    set(gcf,'visible','on');watchoff
            
    
    function callbackfun_001(mysrc,myevt)
        
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        it=str2double(inp2_field.String);
        inp2_field.String=num2str(it);
    end
    
    function callbackfun_002(mysrc,myevt)
        
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        ZG.compare_window_dur=years(str2double(mysrc.String,4));
    end
    
    function go_cb(mysrc,myevt)
        
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        ZmapMessageCenter();
        
        watchon;
        drawnow;
        calculate(method);
    end
    
    function calculate(method)
          % calculate matrix (?)
            
            % check if the times are with limits
            if it > teb || it < t0b
                errordlg('Time out of limits')
                in2 = 'nocal';
                % show_cro
                %return
            end
            % initial parameter
            winlen_days = ZG.compare_window_dur/ZG.bin_dur;
            ti = (it -t0b) / ZG.bin_dur;
            [len, ncu] = size(cumuall); len = len-2;
            var1 = zeros(1,ncu);
            var2 = zeros(1,ncu);
            mean1 = zeros(1,ncu);
            mean2 = zeros(1,ncu);
            as = zeros(1,ncu);
            
            
            switch method
                case 'per'
                    % loop over all grid points for percent
                    for i = 1:ncu
                        mean1(i) = mean(cumuall(1:ti,i));
                        mean2(i) = mean(cumuall(ti:len,i));
                    end    %for i
                    
                    as = -((mean1-mean2)./mean1)*100;
                    
                    strib = 'Change in Percent';
                    stri2 = ['ti=' num2str(ti*days(ZG.bin_dur) + t0b)  ];
                    
                    
                case 'rub'
                    % loop over all point for rubber band
                    for i = 1:ncu
                        mean1(i) = mean(cumuall(1:ti,i));
                        mean2(i) = mean(cumuall(ti+1:ti+winlen_days,i));
                        var1(i) = cov(cumuall(1:ti,i));
                        var2(i) = cov(cumuall(ti+1:ti+winlen_days,i));
                    end %  for i ;
                    as = (mean1 - mean2)./(sqrt(var1/ti+var2/winlen_days));
                    
                    
                case 'ast'
                    % make the AST function map
                    for i = 1:ncu
                        mean1(i) = mean(cumuall(1:ti,i));
                        var1(i) = cov(cumuall(1:ti,i));
                        mean2(i) = mean(cumuall(ti+1:len,i));
                        var2(i) = cov(cumuall(ti+1:len,i));
                    end    %for i
                    as = (mean1 - mean2)./(sqrt(var1/ti+var2/(len-ti)));
                    
                case 'lta'
                    % Calculate LTA
                    cu = [cumuall(1:ti-1,:) ; cumuall(ti+winlen_days+1:len,:)];
                    mean1 = mean(cu(:,:));
                    mean2 = mean(cumuall(ti:ti+winlen_days,:));
                    for i = 1:ncu
                        var1(i) = cov(cu(:,i));
                        var2(i) = cov(cumuall(ti:ti+winlen_days,i));
                    end     % for i
                    as = (mean1 - mean2)./(sqrt(var1/(len-winlen_days)+var2/winlen_days));
                    
                    
                case 'maz'
                    
                    maxlta = zeros(1,ncu);
                    maxlta = maxlta -5;
                    mean1 = mean(cumuall(1:len,:));
                    wai = waitbar(0,'Please wait...');
                    set(wai,'Color',[0.8 0.8 0.8],'NumberTitle','off','Name','Percent done');
                    
                    for i = 1:ncu
                        var1(i) = cov(cumuall(1:len,i));
                    end     % for i
                    for ti = 1:step: len - winlen_days
                        waitbar(ti/len)
                        mean1 = mean(cumuall(1:len,:));
                        mean2 = mean(cumuall(ti:ti+winlen_days,:));
                        for i = 1:ncu
                            var1(i) = cov(cumuall(1:len,i));
                            var2(i) = cov(cumuall(ti:ti+winlen_days,i));
                        end     % for i
                        as = (mean1 - mean2)./(sqrt(var1/len+var2/winlen_days));
                        maxlta2 = [maxlta ;  as ];
                        maxlta = max(maxlta2);
                    end    % for it
                    as = reshape(maxlta,length(gy),length(gx));
                    close(wai)
                    
                otherwise
                    % do nothing?
                    
            end % the switch for "in"
            
            % recreate rectengular matrix
            normlap2=NaN(length(tmpgri(:,1)),1);
            
            normlap2(ll)= as(:);
            %construct a matrix for the color plot
            valueMap=reshape(normlap2,length(yvect),length(xvect));
            
            [n1, n2] = size(cumuall);
            s = cumuall(n1,:);
            normlap2(ll)= s(:);
            %construct a matrix for the color plot
            r=reshape(normlap2,length(yvect),length(xvect));
            ZG.tresh_km = max(r(:));
            
            % find max and min of data for automatic scaling
            %
            ZG.maxc = max(valueMap(:));
            ZG.maxc = fix(ZG.maxc)+1;
            ZG.minc = min(valueMap(:));
            ZG.minc = fix(ZG.minc)-1;
            %plot imge
            %
            det = 'nop';
            old = valueMap;
            vi_cucro(det, valueMap)
    end
    
end

