function afthlp() % autogenerated function wrapper
%Opens an explanation file for aftershock analysis.
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals
open('afthelp');

end
