% Script: plot_McBwtime.m
%
% Script to plot Mc and b as a function of time using the bootstrap
% approach
% Uses the result matrix from calc_McBwtime
% last update: 14.02.2005
% J. Woessner

% Get input
if selt == 'in'
    % Initial values
    nSampleSize = 500;
    nOverlap = 4;
    nMethod = 1;
    nBstSample = 200;
    nMinNumberevents = 50;
    fBinning = 0.1;
    nWindowSize = 5;
    fMcCorr = 0;

    figure_w_normalized_uicontrolunits(...
        'Name','Mc Input Parameter',...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'NextPlot','new', ...
        'units','points',...
        'Visible','off', ...
        'Position',[ 200 200 500 200]);
    axis off

    % Input parameters
    % Get list of Mc computation possibilities
    [labelList2] = calc_Mc;
    %labelList2=[' Max. curvature (MAXC) |Fixed Mc (Mc = Mmin) | GFT-90% | GFT-95% | Best (?) combination (Mc95 - Mc90 - max curvature) | EMR-method | MBS-method (Shi) | MBS-method (Bst)'];
    labelPos = [0.08 0.86  0.8  0.08];
    hndl2=uicontrol(...
        'Style','popup',...
        'Position',labelPos,...
        'Units','normalized',...
        'String',labelList2,...
        'Callback','nMethod=hndl2.Value; ');
    set(hndl2,'value',1);

    field1 = uicontrol('Style','edit',...
        'Position',[.35 .75 .12 .08],...
        'Units','normalized','String',num2str(nSampleSize),...
        'Callback','nSampleSize=str2double(field1.String); field1.String=num2str(nSampleSize);');

    field2 = uicontrol('Style','edit',...
        'Position',[.35 .65 .12 .08],...
        'Units','normalized','String',num2str(nOverlap),...
        'Callback','nOverlap=str2double(field2.String); field2.String=num2str(nOverlap);');

    field3 = uicontrol('Style','edit',...
        'Position',[.35 .55 .12 .08],...
        'Units','normalized','String',num2str(nBstSample),...
        'Callback','nBstSample=str2double(field3.String); field3.String=num2str(nBstSample);');

    field4 = uicontrol('Style','edit',...
        'Position',[.35 .35 .12 .08],...
        'Units','normalized','String',num2str(fBinning),...
        'Callback','fBinning=str2double(field4.String); field4.String=num2str(fBinning);');

    field5 = uicontrol('Style','edit',...
        'Position',[.35 .25 .12 .08],...
        'Units','normalized','String',num2str(nWindowSize),...
        'Callback','nWindowSize=str2double(field5.String); field5.String=num2str(nWindowSize);');

    field6 = uicontrol('Style','edit',...
        'Position',[.35 .45 .12 .08],...
        'Units','normalized','String',num2str(fMcCorr),...
        'Callback','fMcCorr=str2double(field6.String); field6.String=num2str(fMcCorr);');

    field7 = uicontrol('Style','edit',...
        'Position',[.7 .75 .12 .08],...
        'Units','normalized','String',num2str(nMinNumberevents),...
        'Callback','nMinNumberevents=str2double(field1.String); field1.String=num2str(nMinNumberevents);');

    close_button=uicontrol('Style','Pushbutton',...
        'Position',[.60 .05 .15 .12 ],...
        'Units','normalized','Callback','close;done','String','Cancel');

    go_button1=uicontrol('Style','Pushbutton',...
        'Position',[.20 .05 .15 .12 ],...
        'Units','normalized',...
        'Callback',' inpr1=hndl2.Value;close,selt =''ca'';, plot_McBwtime',...
        'String','Go');

    txt1 = text(...
        'Position',[0.01 0.82 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String',' Sample window size');

    txt2 = text(...
        'Position',[0.01 0.7 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String',' Overlap');

    txt3 = text(...
        'Position',[0.01 0.58 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String',' Bootstraps');

    txt4 = text(...
        'Position',[0.01 0.34 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String',' Binning');

    txt5 = text(...
        'Position',[0.01 0.23 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String',' Smooth plot');

    txt6 = text(...
        'Position',[0.01 0.46 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String','Mc correction');

    txt7 = text(...
        'Position',[0.50 0.82 0 ],...
        'HorizontalAlignment','Left',...
        'FontSize',ZmapGlobal.Data.fontsz.s ,...
        'FontWeight','bold',...
        'String','Minimum number');

    set(gcf,'visible','on');
    watchoff
end

if selt == 'ca'

    % Set minimum number to number of moving window
    %nMinNumberevents = nSampleSize;
    % Calulate time series
    [mResult] = calc_McBwtime(ZG.newt2, nSampleSize, nOverlap, nMethod, nBstSample, nMinNumberevents, fBinning,fMcCorr);

    % Plot Mc time series
    if sPar == 'mc'
        fig = figure_w_normalized_uicontrolunits('tag','Mc time series', 'visible','on');
        mMc = filter(ones(1,nWindowSize)/nWindowSize,1,mResult(:,2));
        mMc(1:nWindowSize,1)=mResult(1:nWindowSize,2);
        mMcstd1 = filter(ones(1,nWindowSize)/nWindowSize,1,mResult(:,3));
        mMcstd1(1:nWindowSize,1)=mResult(1:nWindowSize,3);
        ax=axes(fig);
        plot(ax,mResult(:,1),mMc,'-','Linewidth',2,'Color',[0.2 0.2 0.2],'DisplayName','min Mag. Completeness (mMc)');
        hold(ax,'on');
        plot(ax,mResult(:,1),mMc-mMcstd1,'-.','Linewidth',2,'Color',[0.5 0.5 0.5],'DisplayName','mMc - std');
        plot(ax,mResult(:,1),mMc+mMcstd1,'-.','Linewidth',2,'Color',[0.5 0.5 0.5],'DisplayName','mMc + std');
        ylabel(ax,'Mc','Fontweight','bold','FontSize',12);
        set(ax,'tag','smooth_btime_n1000');
        %set(gca,'XTickLabel',[])
        xlim(ax,[(min(mResult(:,1))) (max(mResult(:,1)))]);
        ylim(ax,[floor(min(mMc(:,1))) ceil(max(mMc(:,1)))]);
        xlabel(ax,'Time / [dec. year]','Fontweight','bold','FontSize',12)% ylim([0.85 1.1])
        l1=legend('Mc','\delta Mc');
        %l1=legend('EMR','Std(EMR)','MaxM');
        set(l1,'Fontweight','bold');
        set(ax,'Fontweight','bold','FontSize',10,'Linewidth',2,'Tickdir','out');

    % Plot b time series
    else
        fig=figure_w_normalized_uicontrolunits('tag','b-value time series', 'visible','on');
        mB = filter(ones(1,nWindowSize)/nWindowSize,1,mResult(:,4));
        mB(1:nWindowSize,1)=mResult(1:nWindowSize,4);
        mBstd1 = filter(ones(1,nWindowSize)/nWindowSize,1,mResult(:,3));
        mBstd1(1:nWindowSize,1)=mResult(1:nWindowSize,3);
        ax=axes(fig);
        hp1=plot(ax,mResult(:,1),mB,'-','Linewidth',2,'Color',[0.2 0.2 0.2],'DisplayName','b-value');
        hold(ax,'on');
        hp2=plot(ax,mResult(:,1),mB-mBstd1,'-.','Linewidth',2,'Color',[0.5 0.5 0.5],'DisplayName','mB - std');
        plot(ax,mResult(:,1),mB+mBstd1,'-.','Linewidth',2,'Color',[0.5 0.5 0.5],'DisplayName','mB + std');
        ylabel(ax,'b-value','Fontweight','bold','FontSize',12)
        xlim(ax,[(min(mResult(:,1))) (max(mResult(:,1)))])
        ylim(ax,[floor(min(mB(:,1))) ceil(max(mB(:,1)))])
        xlabel(ax,'Time / [dec. year]','Fontweight','bold','FontSize',12)
        l1=legend(ax,[hp1 hp2],'b-value','\delta b');
        set(l1,'Fontweight','bold')
        set(ax,'Fontweight','bold','FontSize',10,'Linewidth',2,'Tickdir','out')
    end
end
