%   Matlab script to input initial parameters for genas and genascum
%
%                                                R. Zuniga, 4/94

report_this_filefun(mfilename('fullpath'));

minmg = minma;
maxmg = maxma;
magstep = 0.5
%
if isempty(newcat), newcat = a; end   % verify whether to start with
% original catalogue
% make the interface for input
%
figure_w_normalized_uicontrolunits(mess)
clf
set(gcf,'Name','Genas Control Panel');
%  set(gcf,'visible','off');
set(gca,'visible','off');
set(gcf,'pos',[ 0.02  0.6 0.35 0.35])
%par1 = ((teb-t0b)*365)/100;
%
freq_field2=uicontrol('Style','edit',...
    'Position',[.80 .60 .15 .10],...
    'Units','normalized','String',num2str(minmg),...
    'Callback','minmg=str2double(get(freq_field2,''String'')); set(freq_field2,''String'',num2str(minmg));');

freq_field3=uicontrol('Style','edit',...
    'Position',[.80 .45 .15 .10],...
    'Units','normalized','String',num2str(maxmg),...
    'Callback','maxmg=str2double(get(freq_field3,''String'')); set(freq_field3,''String'',num2str(maxmg));');

freq_field=uicontrol('Style','edit',...
    'Position',[.80 .30 .15 .10],...
    'Units','normalized','String',num2str(magstep),...
    'Callback','magstep=str2double(get(freq_field,''String'')); set(freq_field,''String'',num2str(magstep));');


uicontrol('Style','Pushbutton',...
    'Position',[.80 .05 .15 .15 ],...
    'Units','normalized','Callback','web([''file:'' hodi ''/zmapwww/chap8.htm#997197''])','String','Info');

close_button=uicontrol('Style','Pushbutton',...
    'Position',[.60 .05 .15 .15 ],...
    'Units','normalized','Callback','welcome','String','Cancel');

genas_button1=uicontrol('Style','Pushbutton',...
    'Position',[.20 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','welcome,gogenas',...
    'String','Genas');

% genas_button2=uicontrol('Style','Pushbutton',...
%     'Position',[.40 .05 .15 .15 ],...
%     'Units','normalized',...
%     'Callback','welcome,inmakegr',...
%     'String','GenGrid');

txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.65 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'Fontweight','bold',...
    'String','Minimum magnitude:');

txt4 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.48 0 ],...
    'Rotation',0 ,...
    'Fontweight','bold',...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'String','Maximum magnitude:');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.31 0 ],...
    'Rotation',0 ,...
    'Fontweight','bold',...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'String','Magnitude increment (step):');


set(gcf,'visible','on');


