% read hypoellipse and other formated  data into a matrix a that can be used
% in zmap!
%
% Stefan Wiemer; 6/95

report_this_filefun(mfilename('fullpath'));
% This is the info window text
%
titstr='The Data Input Window                        ';
hlpStr= ...
    ['                                                '
    ' Allows you ti Import data into zmap. At this   '
    ' You can either Import the data as ASCII colums '
    ' separated by blanks or as hypoellipsee.        '
    ' It is however possible to modify the input     '
    ' parameter such that you can read almost every  '
    ' catalog format! You have to define the position'
    ' of each of the variables (e.g Year:            '
    ' Column 1 to 2). The default values are         '
    ' hypoellipse (first 36 charcters only).         '
    ' You can read more than 36 characters, but it   '
    ' will take longer. It is usefull to cut the     '
    ' hypo datafile at line 36 (UNIX cut -c 1-36 ...)'
    ' You can costumize the file                     '
    ' /src/loadhypo.m and create a new input variable'
    ' file similar to hypo_de.m. See the Users Guide '
    ' for more details.                              '
    ' To load an ASCII file seperated by blanks      '
    ' switch the popup Menu FORMAT to ASCII COLUMNS. '];



if in == 'initf'


    % add a new label to the list
    labelList=['Hypoellipse | Ascii columns'];

    % add a new option for your own data file format like that
    % if in2 = 3
    % myfor_de     % this read the parameter from the file myfor_de.m
    % end


    if in2 == 1
        hypo_de
    end
    if in2 == 2
        da = 'eq';loadasci; return
    end

    % set up the figure
    [existFlag,figNumber]=figure_exists('Data Input',1);
    newinpWindowFlag=~existFlag;

    % Set up the window Enviroment
    %
    if newinpWindowFlag

        lohy = figure_w_normalized_uicontrolunits(...
            'Units','centimeter','pos',[0 0 13 17],...
            'Name','Data Input',...
            'visible','on',...
            'NumberTitle','off',...
            'MenuBar','none',...
            'Color',color_fbg,...
            'NextPlot','add');
        axis off
    end  % if figure exist

    figure_w_normalized_uicontrolunits(lohy)
    clf

    uicontrol('BackGroundColor',[0.9 0.9 0.9],'Style','Frame',...
        'Position',[0.6 1.5   12  12.5],...
        'Units','centimeter');

    uicontrol('Style','text',...
        'Position',[1 15.0   3  0.8],...
        'Units','centimeter','String','Format:');

    labelList=['Hypoellipse | Ascii columns'];
    labelPos = [6 15.0 3 0.8];
    hndl1=uicontrol(...
        'Style','popup',...
        'Units','centimeter',...
        'Position',labelPos,...
        'String',labelList,...
        'Callback','in2 =get(hndl1,''Value''); loadhypo');

    labelList2=['Lat/Lon in minutes | Lat/Lon in decimales (0-99)'];
    labelPos2 = [1 2.0 6 0.8];
    hndl2=uicontrol(...
        'Style','popup',...
        'Units','centimeter',...
        'Position',labelPos2,...
        'String',labelList2,...
        'BackgroundColor','y');

    uicontrol('Style','text',...
        'Position',[1 16.0   4  0.8],...
        'Units','centimeter','String','No. of Characters:');

    uicontrol('BackGroundColor',color_fbg ,'Style','text',...
        'Position',[1 14   3  0.8],...
        'Units','centimeter','String','Parameter:');

    uicontrol('BackGroundColor',color_fbg ,'Style','text',...
        'Position',[5 14   4  0.8],...
        'Units','centimeter','String','Column No ? to ?');

    uicontrol('BackGroundColor',color_fbg ,'Style','text',...
        'Position',[10 14   2  0.8],...
        'Units','centimeter','String','Divide by:');


    inpnu=uicontrol('Style','edit',...
        'Position',[6 16.0   1  0.8],...
        'Units','centimeter','String',num2str(nu),...
        'Callback','nu=str2double(get(inpnu,''String'')); set(inpnu,''String'',num2str(nu))');

    h1 = 13;
    inpy1=uicontrol('Style','edit',...
        'Position',[6 h1   1  0.8],...
        'Units','centimeter','String',num2str(y1),...
        'Callback','y1=str2double(get(inpy1,''String'')); set(inpy1,''String'',num2str(y1))');

    inpy2=uicontrol('Style','edit',...
        'Position',[8 h1   1  0.8],...
        'Units','centimeter','String',num2str(y2),...
        'Callback','y2=str2double(get(inpy2,''String'')); set(inpy2,''String'',num2str(y2))');

    uicontrol('Style','text',...
        'Position',[1 h1   3  0.8],...
        'Units','centimeter','String','Year');

    h2 = 12;
    inpmo1=uicontrol('Style','edit',...
        'Position',[6 h2   1  0.8],...
        'Units','centimeter','String',num2str(mo1),...
        'Callback','mo1=str2double(get(inpmo1''String'')); set(inpmo1''String'',num2str(mo1)');

    inpmo2=uicontrol('Style','edit',...
        'Position',[8 h2   1  0.8],...
        'Units','centimeter','String',num2str(mo2),...
        'Callback','mo2=str2double(get(inpmo2,''String'')); set(inpmo2,''String'',num2str(mo2))');

    uicontrol('Style','text',...
        'Position',[1 h2   3  0.8],...
        'Units','centimeter','String','Month');

    h3 = 11;
    inpda1=uicontrol('Style','edit',...
        'Position',[6 h3   1  0.8],...
        'Units','centimeter','String',num2str(da1),...
        'Callback','da1=str2double(get(inpda1''String'')); set(inpda1''String'',num2str(da1)');

    inpda2=uicontrol('Style','edit',...
        'Position',[8 h3   1  0.8],...
        'Units','centimeter','String',num2str(da2),...
        'Callback','da2=str2double(get(inpda2,''String'')); set(inpda2,''String'',num2str(da2))');

    uicontrol('Style','text',...
        'Position',[1 h3   3  0.8],...
        'Units','centimeter','String','Day');

    h4 = 10;
    inphr1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(hr1),...
        'Callback','hr1=str2double(get(inphr1''String'')); set(inphr1''String'',num2str(hr1)');

    inphr2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(hr2),...
        'Callback','hr2=str2double(get(inphr2,''String'')); set(inphr2,''String'',num2str(hr2))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Hour');
    h4 = 9;
    inpmi1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(mi1),...
        'Callback','mi1=str2double(get(inpmi1''String'')); set(inpmi1''String'',num2str(mi1)');

    inpmi2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(mi2),...
        'Callback','mi2=str2double(get(inpmi2,''String'')); set(inpmi2,''String'',num2str(mi2))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Minute');


    h4 = 8;
    inpla1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(la1),...
        'Callback','la1=str2double(get(inpla1''String'')); set(inpla1''String'',num2str(la1)');

    inpla2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(la2),...
        'Callback','la2=str2double(get(inpla2,''String'')); set(inpla2,''String'',num2str(la2))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Latitude');

    h4 = 7;
    inplm1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(lm1),...
        'Callback','lm1=str2double(get(inplm1''String'')); set(inplm1''String'',num2str(lm1)');

    inplm2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(lm2),...
        'Callback','lm2=str2double(get(inplm2,''String'')); set(inplm2,''String'',num2str(lm2))');
    inplmc=uicontrol('Style','edit',...
        'Position',[10 h4   1.5  0.8],...
        'Units','centimeter','String',num2str(lmc),...
        'Callback','lmc=str2double(get(inplmc,''String'')); set(inplmc,''String'',num2str(lmc))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Lat minute');

    h4 = 6;
    inplo1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(lo1),...
        'Callback','lo1=str2double(get(inplo1''String'')); set(inplo1''String'',num2str(lo1)');

    inplo2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(lo2),...
        'Callback','lo2=str2double(get(inplo2,''String'')); set(inplo2,''String'',num2str(lo2))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Longitude');

    h4 = 5;
    inpln1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(ln1),...
        'Callback','ln1=str2double(get(inpln1''String'')); set(inpln1''String'',num2str(ln1)');

    inpln2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(ln2),...
        'Callback','ln2=str2double(get(inpln2,''String'')); set(inpln2,''String'',num2str(ln2))');
    inplnc=uicontrol('Style','edit',...
        'Position',[10 h4   1.5  0.8],...
        'Units','centimeter','String',num2str(lnc),...
        'Callback','lnc=str2double(get(inplnc,''String'')); set(inplnc,''String'',num2str(lnc))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Long minute');

    h4 = 4;
    inpde1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(de1),...
        'Callback','de1=str2double(get(inpde1''String'')); set(inpde1''String'',num2str(de1)');

    inpde2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(de2),...
        'Callback','de2=str2double(get(inpde2,''String'')); set(inpde2,''String'',num2str(de2))');

    inpdec=uicontrol('Style','edit',...
        'Position',[10 h4   1.5  0.8],...
        'Units','centimeter','String',num2str(cde),...
        'Callback','cde=str2double(get(inpdec,''String'')); set(inpdec,''String'',num2str(cde))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Depth');

    h4 = 3;
    inpma1=uicontrol('Style','edit',...
        'Position',[6 h4   1  0.8],...
        'Units','centimeter','String',num2str(ma1),...
        'Callback','ma1=str2double(get(inpma1''String'')); set(inpma1''String'',num2str(ma1)');

    inpma2=uicontrol('Style','edit',...
        'Position',[8 h4   1  0.8],...
        'Units','centimeter','String',num2str(ma2),...
        'Callback','ma2=str2double(get(inpma2,''String'')); set(inpma2,''String'',num2str(ma2))');
    inpmac=uicontrol('Style','edit',...
        'Position',[10 h4   1.5  0.8],...
        'Units','centimeter','String',num2str(mac),...
        'Callback','mac=str2double(get(inpmac,''String'')); set(inpmac,''String'',num2str(mac))');

    uicontrol('Style','text',...
        'Position',[1 h4   3  0.8],...
        'Units','centimeter','String','Magnitude');

    uicontrol('Style','Pushbutton',...
        'Position',[3 0.2 1.5 1         ],...
        'Units','centimeter',...
        'Callback','think,in =''readd''; loadhypo',...
        'String','Go');

    uicontrol('Style','Pushbutton',...
        'Position',[ 5 0.2 1.5 1        ],...
        'Units','centimeter',...
        'Callback','zmaphelp(titstr,hlpStr)',...
        'String','Info');

    uicontrol('Style','Pushbutton',...
        'Position',[ 8 0.2 1.5 1        ],...
        'Units','centimeter',...
        'Callback','close;done',...
        'String','Cancel');



end   % if in = initf

if in == 'readd'

    % read in the data file

    [file1,path1] = uigetfile([hoda '*'],' Earthquake Datafile');
    if length(file1) < 2
        return
    end
    % read the first three lines as a test...
    fid = fopen([path1 file1],'r');
    zmap_message_center.set_info(' ','Loading data...hang on');
    so = fscanf(fid,'%c',[nu+1, inf]);
    fclose(fid);
    so = so';
    disp('First Three rows - does it look right?')
    so(1:3,:)


    n = max([y1,y2,mi1,mi1,mo1,mo2,da1,da2,de1,de1,ma1,ma2,hr1,hr2,lo1,lo2,la1,la2,lm1,lm2,ln1,ln2]);
    for  i = 1:n
        so(:,i) = strrep(so(:,i)',' ','0')';
    end

    yr = str2double(so(:,y1:y2));
    mo = str2double(so(:,mo1:mo2));
    da = str2double(so(:,da1:da2));
    hr = str2double(so(:,hr1:hr2));
    mi= str2double(so(:,mi1:mi2));
    lat= str2double(so(:,la1:la2));
    lon= str2double(so(:,lo1:lo2));
    latm= str2num(so(:,lm1:lm2))/lmc;
    lonm= str2num(so(:,ln1:ln2))/lnc;
    dep= str2num(so(:,de1:de2))/cde;
    mag= str2num(so(:,ma1:ma2))/mac;

    if get(hndl2,'Value') == 1;
        latm = latm*10/6;
        lonm = lonm*10/6;
    end

    a = [ -lon-lonm lat+latm yr mo da mag dep hr mi];

    a = ZmapCatalog(a); % col 3 was just year, not decyear
    a.sort('Date'); 
    
    minmag = max(a.Magnitude) -0.2;       %  as a default to be changed by inpu

    %  ask for input parameters
    %
    watchoff
    close(lohy)
    clear so is yr da mag dep hr mi lat latm lon lonm mo
    ZG=ZmapGlobal.Data;ZG.mainmap_plotby='depth';
    do = 'view';
    inpu

end   % if in in readd
