function InitVariables(obj)
		%No Zmap stuff needed anymore
		%some basic parameters, I will add addition parameters later 
		%if needed e.g. bootstrap option
		obj.CalcParameter = struct(	'Tau_min',1,...
						'Tau_max',10,...
						'XMagEff',1.5,...
						'XMagFactor',0.5,...
						'RadiusFactor',10,...
						'ProbObs',0.95,...
						'EpiError',1.5,...
						'DepthError',2,...
						'GK_Method',1,...
						'GK_SetMain',false,...
						'Sli_Type',1,...
						'MainMag',4,...
						'BackTime',30,...
						'ForeTime',30,...
						'MinRad',5,...
						'MagRadScale',0.59,...
						'MagRadConst',2.44);
						

						
		%from Reasenberg decluster (variable Info)
		% variables given by inputwindow
		%
		% RadiusFactor:	rfact  	is factor for interaction radius for dependent events (default 10)
		% XMagEff:	xmeff  	is "effective" lower magnitude cutoff for catalog,it is raised 
		%         		by a factor xk*cmag1 during clusters (default 1.5)
		% XMagFactor:	xk	is the factor used in xmeff    (default .5)
		% Tau_min:	taumin 	is look ahead time for not clustered events (default one day)
		% Tau_max:	taumax 	is maximum look ahead time for clustered events (default 10 days)
		% ProbObs:	P      	to be P confident that you are observing the next event in 
		%       		the sequence (default is 0.95)
		
		
		%From Slider 
		%Selection Method:	Time: earthquakes are process in temporal order (clusterSLIDERtime)
		%			Magnitude: earthquakes are process by magnitude size (clusterSLIDERmag)
		%MainMag:		minimum mainmag magnitude
		%BackTime:		time before an earthquake in days
		%ForeTime:		time window following an earthquake in days
		%MinRad:		Minimum radius used for searching triggered events
		%MagRadScale:		Sets how much the search radius varies with magnitude size
		%MagRadConst:		Constant subtracted from the magnitude scaled search radius
	
	end
