function fixax_vertical(re3);
    % Script: fixax_vertical.m
    % Make dialog interface for the fixing of vertical colomap
    %
    % last update: 07.07.2004
    % jochen.woessner@sed.ethz.ch
    
    report_this_filefun(mfilename('fullpath'));
    
    % Initialize
    fre = 0;
    
    % Figure setup
    f = figure_w_normalized_uicontrolunits();
    clf
    set(gca,'visible','off')
    set(f,'Units','pixel','NumberTitle','off','Name','Input Parameters');
    set(f,'pos',[ ZG.welcome_pos ZG.welx+200 ZG.wely-50])
    
    
    % Create a dialog box to input some parameters
    %
    
    tmp_min = min(re3(:),[],'omitnan');
    tmp_max = max(re3(:),[],'omitnan');
    inp2_field  = uicontrol('Style','edit',...
        'Position',[.80 .775 .18 .15],...
        'Units','normalized',...
        'String',num2str(tmp_min),...
        'Value',tmp_min,...
        'Callback',@min_callback);
    
    text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0. 0.9 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input minimum of z-axis:');
    
    
    text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0. 0.65 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input maximum of z(or b)-values:');
    
    inp3_field=uicontrol('Style','edit',...
        'Position',[.80 .575 .18 .15],...
        'Units','normalized',...
        'String',num2str(tmp_max),...
        'Value',tmp_max,...
        'Callback', @max_callback);
    
    uicontrol('Style','Pushbutton',...
        'Position', [.60 .07 .15 .15 ],...
        'Units','normalized','Callback',@close_callback,'String','Cancel');
    
    uicontrol('Style','Pushbutton',...
        'Position',[.25 .05 .15 .15 ],...
        'Units','normalized',...
        'Callback',@go_callback,...
        'String','Go');
    
    freeze_button = uicontrol(...
        'BackgroundColor',[ 0.7 0.7 0.7 ],...
        'Callback',@freeze_colorbar_callback,...
        'ForegroundColor',[ 0 0 0 ],...
        'Position',[ 0.25 0.30 0.4 0.15 ],...
        'String','Freeze Colorbar? ',...
        'Style','checkbox',...
        'Units','normalized',...
        'Visible','on');
    
    set(f,'visible','on');watchoff
    function min_callback(mysrc,~)
        % automatically created callback function from text
        mysrc.Value = str2double(mysrc.String);
    end
    
    function max_callback(mysrc,~)
        % automatically created callback function from text
        mysrc.Value = str2double(mysrc.String);
    end
    
    function close_callback(mysrc, ~)
        % automatically created callback function from text
        zmap_message_center();
    end
    function go_callback(mysrc,myevt)
        % automatically created callback function from text
        
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        fix2=inp3_field.Value;
        fix1=inp2_field.Value;
        zmap_message_center();
        axes(h1);
        caxis([fix1 fix2]);
        hold off;
        %h5 = colorbar('horiz');
        %set(h5,'Pos',[0.35 0.07 0.4 0.02],...
        %    'FontWeight','bold',...
        %    'TickDir','out',...
        %    'FontSize',ZmapGlobal.Data.fontsz.s,...
        %    'Linewidth',1.5);
        watchoff;
    end
    function freeze_colorbar_callback(mysrc,~)
        % automatically created callback function from text
        fre = mysrc.Value;
    end
end
