%  brand2  calculates synthetic b distributions based on
%  a random permutation of original magnitude values,
%  it then compares it to original b map using bvalmapt
%                                                 Ram�n Z��iga 9/2000
%                          Operates on a
%
report_this_filefun(mfilename('fullpath'));

% first create a new catalog with original data changing the year values

lengtha = length(a);
conca = a;
conca(:,3) = conca(:,3) + 500;  % add 500 to years to make it a consecutive sequence

% now change magnitudes by a random permutation
conca(:,6) = conca(randperm(lengtha),6);  % permuted magnitudes

%paste the two catalogs to get a concatenated set
a(lengtha+1:lengtha*2,:) = conca;

minnu = 40;  % minimum number of events in each period
t4 = a(length(a),3);
t3 = a(lengtha+1,3);
t2 = a(lengtha,3);
t1 = a(1,3);

%stri = [  ' Synthetic b map comparison for ' name  ];
% make the interface
%
figure_w_normalized_uicontrolunits(...
    'Name','Grid Input Parameter',...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'NextPlot','new', ...
    'units','points',...
    'Visible','off', ...
    'Position',[ wex+200 wey-200 450 250]);
axis off
labelList2=['Weighted LS - automatic Mcomp | Weighted LS - no automatic Mcomp '];
labelPos = [0.2 0.7  0.6  0.08];
hndl2=uicontrol(...
    'Style','popup',...
    'Position',labelPos,...
    'Units','normalized',...
    'String',labelList2,...
    'Callback','inb2 =get(hndl2,''Value''); ');



labelList=['Maximum likelihood - automatic Mcomp | Maximum likelihood  - no automatic Mcomp '];
labelPos = [0.2 0.8  0.6  0.08];
hndl1=uicontrol(...
    'Style','popup',...
    'Position',labelPos,...
    'Units','normalized',...
    'String',labelList,...
    'Callback','inb1 =get(hndl1,''Value''); ');


% creates a dialog box to input grid parameters
%
freq_field=uicontrol('Style','edit',...
    'Position',[.60 .50 .22 .10],...
    'Units','normalized','String',num2str(ra),...
    'Callback','ra=str2double(get(freq_field,''String'')); set(freq_field,''String'',num2str(ra));');

freq_field2=uicontrol('Style','edit',...
    'Position',[.60 .40 .22 .10],...
    'Units','normalized','String',num2str(dx),...
    'Callback','dx=str2double(get(freq_field2,''String'')); set(freq_field2,''String'',num2str(dx));');

freq_field3=uicontrol('Style','edit',...
    'Position',[.60 .30 .22 .10],...
    'Units','normalized','String',num2str(dy),...
    'Callback','dy=str2double(get(freq_field3,''String'')); set(freq_field3,''String'',num2str(dy));');

close_button=uicontrol('Style','Pushbutton',...
    'Position',[.60 .05 .15 .12 ],...
    'Units','normalized','Callback','close;done','String','Cancel');

go_button1=uicontrol('Style','Pushbutton',...
    'Position',[.20 .05 .15 .12 ],...
    'Units','normalized',...
    'Callback','inb1 =get(hndl1,''Value'');inb2 =get(hndl2,''Value'');close,sel =''ca'', bvalmapt',...
    'String','Go');

text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.20 1.0 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.l ,...
    'FontWeight','bold',...
    'String','Automatically estimate magn. of completeness?   ');
txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.30 0.64 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.l ,...
    'FontWeight','bold',...
    'String',' Grid Parameter');
txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.42 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.m ,...
    'FontWeight','bold',...
    'String','Spacing in x (dx) in deg:');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.32 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.m ,...
    'FontWeight','bold',...
    'String','Spacing in y (dy) in deg:');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.53 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.m,...
    'FontWeight','bold',...
    'String','Constant Radius in km:');
set(gcf,'visible','on');
watchoff



