report_this_filefun(mfilename('fullpath'));


switch(ac3)

    case 'new'


        sl2 = figure_w_normalized_uicontrolunits( ...
            'Name','Slice',...
            'NumberTitle','off', ...
            'backingstore','on',...
            'NextPlot','add', ...
            'Visible','on', ...
            'Position',[ (fipo(3:4) - [600 500]) ZmapGlobal.Data.map_len]);

        matdraw


        uicontrol('BackGroundColor',[0.8 0.8 0.8],'Units','normal',...
            'Position',[.0 .94 0.10 .06],'String',' Topo (contour) ',...
             'Callback','ac2 = ''topo''; myslicer;')

        uicontrol('BackGroundColor',[0.8 0.8 0.8],'Units','normal',...
            'Position',[.0 .88 0.10 .06],'String',' Topo (render) ',...
             'Callback','ac2 = ''topos''; myslicer;')

        uicontrol('BackGroundColor',[0.8 0.8 0.8],'Units','normal',...
            'Position',[.0 .80 0.10 .06],'String',' Topo (render2) ',...
             'Callback','ac2 = ''topos2''; myslicer;')

        uicontrol('BackGroundColor',[0.8 0.8 0.8],'Units','normal',...
            'Position',[.0 .0 0.1 .04],'String','Fix View ',...
             'Callback','ac2 = ''equal''; myslicer;')

        uicontrol('BackGroundColor',[0.8 0.8 0.8],'Units','normal',...
            'Position',[.1 .0 0.1 .04],'String','Max R ',...
             'Callback','ac2 = ''setr''; myslicer;')

        uicontrol('BackGroundColor',[0.8 0.8 0.8],'Units','normal',...
            'Position',[.9 .0 0.15 .04],'String','Fix color scale ',...
             'Callback','ac2 = ''setc''; myslicer;')


        labelList=[' flat | interp | faceted '];
        labelPos = [0.9 0.93 0.10 0.05];
        hndl3=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva1''; chooseint');


        labelList=[' hsv | hot | jet | cool | pink | gray | bone | invjet  '];
        labelPos = [0.9 0.85 0.10 0.05];
        hndl2=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva2''; chooseint');

        labelList=[' Above  | NS | EW | angle'];
        labelPos = [0.9 0.75 0.10 0.05];
        hndl1=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva3''; chooseint');


        labelList=[' EQ  | No EQ '];
        labelPos = [0.9 0.65 0.10 0.05];
        hndl4=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva4''; chooseint');


        labelList=[' Faults  | No Faults '];
        labelPos = [0.9 0.55 0.10 0.05];
        hndl5=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva5''; chooseint');



        labelList=[' Coast  | No Coast '];
        labelPos = [0.9 0.45 0.10 0.05];
        hndl6=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva6''; chooseint');




        labelList=[' Main  | No Main '];
        labelPos = [0.9 0.35 0.10 0.05];
        hndl7=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva7''; chooseint');

        labelList=[' Well | No Well '];
        labelPos = [0.9 0.25 0.10 0.05];
        hndl7=uicontrol(...
            'Style','popup',...
            'Units','normalized',...
            'Position',labelPos,...
            'Value',1,...
            'String',labelList,...
            'BackgroundColor',[0.7 0.7 0.7]',...
            'Callback','ac3 = ''eva8''; chooseint');





    case 'eva1'
        in3 =get(hndl3,'Value');
        if in3 == 1 ; shading flat ; end
        if in3 == 2 ; shading interp ; end
        if in3 == 3 ; shading faceted ; end

    case 'eva2'
        in3 =get(hndl2,'Value');
        if in3 == 1 ; colormap(hsv) ; end
        if in3 == 2 ; colormap(hot) ; end
        if in3 == 3 ; colormap(jet) ; end
        if in3 == 4 ; colormap(cool) ; end
        if in3 == 5 ; colormap(pink) ; end
        if in3 == 6 ; colormap(gray) ; end
        if in3 == 7 ; colormap(bone) ; end
        if in3 == 8; co = jet; co = co(64:-1:1,:); colormap(co) ; end

    case 'eva3'
        in3 =get(hndl1,'Value');
        if in3 == 1 ; view([-90 90]) ; end
        if in3 == 2 ; view([-90 0]) ; end
        if in3 == 3 ; view([0  0]) ; end
        if in3 == 4 ; view([-120  25]) ; end

    case 'eva4'

        in3 =get(hndl4,'Value');
        if in3 == 1 ; ploe = plot3(ZG.a.Latitude,ZG.a.Longitude,-ZG.a.Depth,'.w','MarkerSize',1) ; end
        if in3 == 2 ; delete(ploe);  end

    case 'eva5'
        in3 =get(hndl5,'Value');
        if in3 == 1 ; plof = plot3(faults(:,2),faults(:,1),faults(:,1)*0,'m') ; end
        if in3 == 2 ; delete(plof) ; end


    case 'eva6'
        in3 =get(hndl6,'Value');
        if in3 == 1 ; ploc = plot3(coastline(:,2),coastline(:,1),coastline(:,1)*0,'w','Linewidth',2) ; end
        if in3 == 2 ; delete(ploc) ; end

    case 'eva7'
        in3 =get(hndl7,'Value');
        if in3 == 1 
            epimax2 = plot3(maepi(:,2),maepi(:,1),-maepi(:,7),'hm');
            set(epimax2,'LineWidth',1.5,'MarkerSize',12,...
                'MarkerFaceColor','y','MarkerEdgeColor','k')
        end


    case 'eva8'
        in3 =get(hndl7,'Value');
        if in3 == 1 
            l = well(:,1) >= ax(3) & well(:,1) <= ax(4) & well(:,2) >= ax(1)  & well(:,2) <= ax(2) & ...
                -well(:,3) >= ax(5) & -well(:,3) <= ax(6) |  isinf(well(:,1)) == 1 ;
            epimax2 = plot3(well(l,2),well(l,1),-well(l,3),'w');
            set(epimax2,'LineWidth',2);
        end
        if in3 == 2 ; delete(epimax2) ; end


end



