function comcat() % autogenerated function wrapper
    % turned into function by Celso G Reyes 2017
    
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    titStr ='Combining two catalogs';
    %TODO fix this, it's a mixture of old and new a
    report_this_filefun(mfilename('fullpath'));
    
    messtext= ...
        ['                                                '
        ' To combine two catalogs please input the       '
        ' second catalog filename. The data will be      '
        ' sorted in time                                 '];
    
    error('unimplemented');
    
    [file1,path1] = uigetfile('*.mat',' Second Earthquake Datafile');
