%
report_this_filefun(mfilename('fullpath'));
%
%  This file display avaible information about a dataset
%
%  Stefan Wiemer 12/94

% This is the info window text
%
ttlStr='Information about the current dataset         ';
hlpStr1dainf = ...
    ['                                                '
    ' This window contains information about the     '
    ' current dataset. You can enter any additional  '
    ' information in this window.                    '
    '                                                '
    ' You should try to document as much information '
    ' as possible about your data!                   '
    '                                                '
    ' In order to save this information you have to  '
    ' select SAVE and save the current dataset       '
    ' information along with the current catalog and '
    ' overlay information in a file.                 '
    '                                                '];

%  Create new figure
% Find out of figure already exists
%
[existFlag,figNumber]=figure_exists('Dataset Info',1);
newdatinfdowFlag=~existFlag;

% Set up the datinf window Enviroment
%
if newdatinfdowFlag
    dainf = figure_w_normalized_uicontrolunits( ...
        'Name','Dataset Info',...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'NextPlot','new', ...
        'Color',[0.7 0.7 0.7],...
        'Visible','off', ...
        'Position',[ fipo(3)-600 fipo(4)-500 winx-100 winy-100]);

    orient tall
    axis off

    fr = uicontrol(gcf,...
        'Units','normalized',...
        'Style','frame',...
        'BackgroundColor' ,[1.0 1.0 0.7]',...
        'Position',[0.1 0.1 0.8 0.7]);

    if isempty(infstri) == 1
        infstri = ' Please enter information about the dataset';
    end

    uic = uicontrol(gcf,...
        'Units','normalized',...
        'Style','edit',...
        'String',infstri,...
        'BackgroundColor' ,[1.0 1.0 1.0]',...
        'Max',2,...
        'Position',[0.12 0.12 0.75 0.65]);

    % show buttons  for various analyses programs:

    uicontrol('Units','normal',...
        'Position',[.0 .90 .10 .09],'String','Print ',...
         'Callback','myprint')

    uicontrol('Units','normal',...
        'Position',[.2 .90 .10 .09],'String','Close ',...
         'Callback','infstri = get(uic,''String'');f1=gcf; f2=gpf; set(f1,''Visible'',''off'');')

    uicontrol('Units','normal',...
        'Position',[.4 .90 .10 .09 ],'String','Info ',...
         'Callback','zmaphelp(ttlStr,hlpStr1dainf)')

    uicontrol('Units','normal',...
        'Position',[.6 .90 .10 .09 ],'String','Save',...
         'Callback','eval(catSaveb)');

    catSaveb =...
        ['infstri = get(uic,''String'');',...
        'zmap_message_center.set_info(''Save Data'',''  '');think;',...
        '[file1,path1] = uiputfile(fullfile(hodi, ''eq_data'', ''*.mat''), ''Earthquake Datafile'');',...
        'if length(file1) > 1 , sapa2 = [''save '' path1 file1 '' a faults main mainfault coastline infstri ''],',...
        'eval(sapa2) ,end, done'];


end   % if fig exist

figure_w_normalized_uicontrolunits(dainf)
set(uic,'String',infstri);
set(gcf,'Visible','on')

