report_this_filefun(mfilename('fullpath'));
%
%
% make another dialog interface and call maxzlta
%
%initial values
iwl3 = 1.;
step = 3;


figure_w_normalized_uicontrolunits(mess)
set(gcf,'visible','off')
clf
set(gcf,  'Name','MAXZ Input Parameters');
set(gca,'visible','off');
set(gcf,'Units','points','pos',[ wex wey 500 200])

% creates a dialog box to input some parameters
%
freq_field=uicontrol('Style','edit',...
    'Position',[.70 .60 .17 .10],...
    'Units','normalized','String',num2str(iwl3),...
    'Callback','iwl3=str2double(freq_field.String); freq_field.String=num2str(iwl3);');

inp2_field=uicontrol('Style','edit',...
    'Position',[.70 .40 .17 .10],...
    'Units','normalized','String',num2str(step),...
    'Callback','step=str2double(inp2_field.String); inp2_field.String=num2str(step);');

close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','zmapmenu','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','welcome,in2=''calma'';in=''maz'';show_map',...
    'String','Go');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.65 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Please input window length in years (iwl):');

txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.40 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Please input step width in bins:');

set(gcf,'visible','on')
