function eq_dep() % autogenerated function wrapper
%  earthquake_depth.m
% August 95 by Zhong Lu
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals

report_this_filefun(mfilename('fullpath'));

[existFlag,figNumber]=figure_exists('Depth vs Earthquake Number',1);

newWindowFlag=~existFlag;

if newWindowFlag
    mif66 = figure_w_normalized_uicontrolunits( ...
        'Name','Depth vs Earthquake Number',...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'backingstore','on',...
        'NextPlot','add', ...
        'Visible','off', ...
        'Position',[ (fipo(3:4) - [300 500]) ZmapGlobal.Data.map_len]);

    
    matdraw
    hold on

end
figure_w_normalized_uicontrolunits(mif66)
hold on

x = [1:length(mi)]';
[ss,ssi]=sort(ZG.a.Depth);
plot(x,ss,'go');

grid
%set(gca,'box','on',...
%        'SortMethod','childorder','TickDir','out','FontWeight',...
%        'bold','FontSize',ZmapGlobal.Data.fontsz.m,'Linewidth',1.2);

ylabel('Depth of Earthquake','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m);
xlabel('Earthquake Number','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m);
hold off;

done

end
