%
% make dialog interface for the fixing of colomap
%


% Input Rubberband
%
report_this_filefun(mfilename('fullpath'));
fre = 0;


%initial values
f = figure_w_normalized_uicontrolunits();
set(gca,'visible','off')
set(f,'Units','pixel','NumberTitle','off','Name','Input Parameters');

set(f,'pos',[ wex  wey welx+200 wely-50])


% creates a dialog box to input some parameters
%

inp2_field  = uicontrol('Style','edit',...
    'Position',[.80 .775 .18 .15],...
    'Units','normalized','String',num2str(min(min(re3))),...
    'Callback','fix1=str2double(get(inp2_field,''String''));set(inp2_field,''String'',num2str(fix1));');

txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.9 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold',...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'String','Please input minimum of z-axis:');


txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.65 0 ],...
    'Rotation',0 ,...
    'FontWeight','bold',...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'String','Please input maximum of z(or b)-values:');

inp3_field=uicontrol('Style','edit',...
    'Position',[.80 .575 .18 .15],...
    'Units','normalized','String',num2str(max(max(re3))),...
    'Callback','fix2=str2double(get(inp3_field,''String'')); set(inp3_field,''String'',num2str(fix2));');

%end   % if in = rub        ->no if no end

close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','welcome','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','fix2=str2num(get(inp3_field,''String''));fix1=str2num(get(inp2_field,''String''));welcome;axes(h1);caxis([fix1 fix2]);hold off; h5 = colorbar(''vert'') ;set(h5,''Pos'',[apo(1)+apo(3)+0.05 apo(2) 0.03 apo(4)],''FontWeight'',''bold'',''FontSize'',ZmapGlobal.Data.fontsz.m);watchoff',...
    'String','Go');

freeze_button = uicontrol(...
    'BackgroundColor',[ 0.7 0.7 0.7 ],...
    'Callback','fre = get(freeze_button,''Value'');',...
    'ForegroundColor',[ 0 0 0 ],...
    'Position',[ 0.25 0.30 0.4 0.15 ],...
    'String','Freeze Colorbar? ',...
    'Style','checkbox',...
    'Units','normalized',...
    'Visible','on');


set(f,'visible','on');watchoff


