function fixax2(re3) % autogenerated function wrapper
    %
    % make dialog interface for the fixing of colomap
    %
    % turned into function by Celso G Reyes 2017
    global fre;
    global_requestor='fixax2' % used by get_zmap_globals
    get_zmap_globals % initialize globals for this function
    
    
    
    % Input Rubberband
    %
    report_this_filefun(mfilename('fullpath'));
    fre = 0;
    
    %h5 is the colorbar
    set(h5,'Visible','off')
    
    %initial values
    f = figure_w_normalized_uicontrolunits();
    set(gca,'visible','off')
    set(f,'Units','pixel','NumberTitle','off','Name','Input Parameters');
    
    set(f,'pos',[ ZG.welcome_pos ZG.welx+200 ZG.wely-50])
    
    tmp_min = min(re3(:),[],'omitnan');
    tmp_max = max(re3(:),[],'omitnan');
    
    % creates a dialog box to input some parameters
    %
    
    inp2_field  = uicontrol('Style','edit',...
        'Position',[.80 .775 .18 .15],...
        'Units','normalized',...
        'String',num2str(tmp_min),...
        'Value',tmp_min,...
        'callback',@min_callback);
    
    text(...
        'Position',[0. 0.9 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input minimum of z-axis:');
    
    
    text(...
        'Position',[0. 0.65 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input maximum of z(or b)-values:');
    
    inp3_field=uicontrol('Style','edit',...
        'Position',[.80 .575 .18 .15],...
        'Units','normalized',...
        'String',num2str(tmp_max),...
        'Value',tmp_max,...
        'callback',@max_callback);
    
    uicontrol('Style','Pushbutton',...
        'Position', [.60 .07 .15 .15 ],...
        'Units','normalized','callback',@close_callback,'String','Cancel');
    
    uicontrol('Style','Pushbutton',...
        'Position',[.25 .05 .15 .15 ],...
        'Units','normalized',...
        'callback',@go_callback,...
        'String','Go');
    
    freeze_button = uicontrol(...
        'Style','checkbox',...
        'callback',@freeze_colorbar_callback,...
        'Position',[ 0.25 0.30 0.4 0.15 ],...
        'String','Freeze Colorbar? ',...
        'Units','normalized',...
        'Visible','on');
    
    set(f,'visible','on');watchoff
    
    function min_callback(mysrc,myevt)
        % automatically created callback function from text
        mysrc.Value = str2double(mysrc.String);
    end
    
    function max_callback(mysrc,myevt)
        % automatically created callback function from text
        mysrc.Value = str2double(mysrc.String);
    end
    
    function close_callback(mysrc,myevt)
        % automatically created callback function from text
        callback_tracker(mysrc,myevt,mfilename('fullpath'),'close_callback');
        zmap_message_center();
    end
    
    function go_callback(mysrc,myevt)
        % automatically created callback function from text
        callback_tracker(mysrc,myevt,mfilename('fullpath'),'go_callback');
        fix2=inp3_field.Value;
        fix1=inp2_field.Value;
        zmap_message_center();
        axes(h1);
        caxis([fix1 fix2]);
        hold off;
        h5 = colorbar('horiz');
        set(h5,'Pos',[0.35 0.07 0.4 0.02],...
            'FontWeight','bold',...
            'TickDir','out',...
            'FontSize',ZmapGlobal.Data.fontsz.s,...
            'Linewidth',1.5);
        watchoff;
    end
    
    function freeze_colorbar_callback(mysrc,myevt)
        % automatically created callback function from text
        callback_tracker(mysrc,myevt,mfilename('fullpath'),'freeze_colorbar_callback');
        fre = mysrc.Value;
    end
end
