report_this_filefun(mfilename('fullpath'));

clf
set(gca,'visible','off');

txt4 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.05 0.54 0 ],...
    'Rotation',0 ,...
    'FontSize',16 ,...
    'String', 'Select using the mouse the lower left orner  ');


txt4B  = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.05 0.40 0 ],...
    'Rotation',0 ,...
    'FontSize',16 ,...
    'String', 'and then the upper right  corner  on the map');

pause(0.1)
makecumu
