report_this_filefun(mfilename('fullpath'));
%
%
% make another dialog interface and call cin_lta
%
%initial values
iwl3 = 1;
nustep = 10;


figure_w_normalized_uicontrolunits(mess)
clf
set(gcf,'Name','Movie Parameter Input ');
set(gca,'visible','off');
set(gcf,'pos',[ wex wey 400 250]);

% creates a dialog box to input some parameters
%
freq_field=uicontrol('Style','edit',...
    'Position',[.80 .60 .12 .10],...
    'Units','normalized','String',num2str(iwl3),...
    'Callback','iwl3=str2double(freq_field.String); freq_field.String=num2str(iwl3);');

inp2_field=uicontrol('Style','edit',...
    'Position',[.80 .40 .12 .10],...
    'Units','normalized','String',num2str(nustep),...
    'Callback','nustep=str2double(inp2_field.String); inp2_field.String=num2str(nustep);');

close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','zmapmenu','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','welcome,runcilta',...
    'String','Go');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.65 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Please input window length in years (iwl):');

txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.40 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Please input number of movie-frames:');

set(gcf,'visible','on')
