%
% make another dialog interface and call cin_lta

report_this_filefun(mfilename('fullpath'));
%
%initial values
minval = 1.0
maxval = 4;
nustep = 10;


figure_w_normalized_uicontrolunits(mess)

set(gcf,'visible','off')
clf

set(gcf, 'Name','Movie Parameter Input ');
set(gca,'visible','off');
set(gcf,'pos',[ZG.welcome_pos 450 250]);

% creates a dialog box to input some parameters
%
freq_field2=uicontrol('Style','edit',...
    'Position',[.80 .80 .12 .10],...
    'Units','normalized','String',num2str(minval),...
    'Callback','minval=str2double(freq_field2.String); freq_field2.String=num2str(minval);');

freq_field=uicontrol('Style','edit',...
    'Position',[.80 .60 .12 .10],...
    'Units','normalized','String',num2str(maxval),...
    'Callback','maxval=str2double(freq_field.String); freq_field.String=num2str(maxval);');

inp2_field=uicontrol('Style','edit',...
    'Position',[.80 .40 .12 .10],...
    'Units','normalized','String',num2str(nustep),...
    'Callback','nustep=str2double(inp2_field.String); inp2_field.String=num2str(nustep);');

close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','zmapmenu','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback',' zmap_message_center();runcimaz',...
    'String','Go');

txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.85 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Please input minimum LTA window length in years:');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.65 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Please input maximum LTA window length in years:');

txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.40 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Please step width in years:');

set(gcf,'visible','on')
