
%   Matlab script to input initial parameters for circle0 routine
%   in main Map Window
%                                                R. Zuniga, 6/94

report_this_filefun(mfilename('fullpath'));
%
if isempty(ZG.newcat), ZG.newcat = a; end   % verify whether to start with
% original catalogue
% make the interface for input
%
figure_w_normalized_uicontrolunits(mess)
clf;
cla;
set(gcf,'Name','Circle-Map Control Panel');
%  set(gcf,'visible','off');
set(gca,'visible','off');
set(gcf,'pos',[ 0.22  0.4 0.30 0.30])

%
freq_field1=uicontrol('Style','edit',...
    'Position',[.80 .70 .15 .10],...
    'Units','normalized','String',num2str(ni),...
    'Callback','ni=str2double(freq_field1.String); freq_field1.String=num2str(ni);');

freq_field2=uicontrol('Style','edit',...
    'Position',[.80 .55 .15 .10],...
    'Units','normalized','String',num2str(rad),...
    'Callback','rad=str2double(freq_field2.String); freq_field2.String=num2str(rad);');

freq_field3=uicontrol('Style','edit',...
    'Position',[.70 .40 .22 .10],...
    'Units','normalized','String',num2str(ya0,5),...
    'Callback','ya0=str2double(freq_field3.String); freq_field3.String=num2str(ya0,6);');

freq_field4=uicontrol('Style','edit',...
    'Position',[.70 .25 .22 .10],...
    'Units','normalized','String',num2str(xa0,6),...
    'Callback','xa0=str2double(freq_field4.String); freq_field4.String=num2str(xa0,6);');

close_button=uicontrol('Style','Pushbutton',...
    'Position',[.05 .85 .15 .1 ],...
    'Units','normalized','Callback', 'welcome','String','Cancel');

button1=uicontrol('Style','Pushbutton',...
    'Position',[.35 .15 .3 .1 ],...
    'Units','normalized',...
    'Callback',' ic = 1; circle0',...
    'String','Center by Cursor');

button2=uicontrol('Style','Pushbutton',...
    'Position',[.10 .05 .2 .1 ],...
    'Units','normalized',...
    'Callback','welcome, ic = 2; circle0',...
    'String','Fix Radius');

button3=uicontrol('Style','Pushbutton',...
    'Position',[.70 .05 .3 .1 ],...
    'Units','normalized',...
    'Callback','welcome,ic = 3; circle0',...
    'String','ni Closest Events');

txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.75 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Number of events (ni):');

txt4 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.58 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Radius (km):');

txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.41 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Latitude of center:');

txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.24 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Longitude of center:');

set(gcf,'visible','on');


