report_this_filefun(mfilename('fullpath'));
%
%
% make another dialog interface and
%
figure_w_normalized_uicontrolunits(mess)
clf
%initial values
iwl3 = 1;
nustep = 10;




set(gca,'visible','off');
set(gcf,'pos',[wex wey 400 250]);

% creates a dialog box to input some parameters
%

inp2_field=uicontrol('Style','edit',...
    'Position',[.80 .40 .12 .10],...
    'Units','normalized','String',num2str(nustep),...
    'Callback','nustep=str2double(get(inp2_field,''String'')); set(inp2_field,''String'',num2str(nustep));');

close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','zmapmenu','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','welcome,runcias',...
    'String','Go');


txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.40 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m,...
    'FontWeight','bold',...
    'String','Please input number of movie-frames:');

set(gcf,'visible','on')
