% This subroutine assigns Parameter values for the grid
% which is used to calculate a Max Z value map.
% dx, dy is the grid spacing in degrees.
% For each one of the grid points, Ni events are counted.
%

report_this_filefun(mfilename('fullpath'));

% initial values
%
dx = 1.00;
dy = 1.00 ;
ni = 100;

%
% make the interface
%
figure_w_normalized_uicontrolunits(...
    'Name','Alarm Cube Input Parameter',...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'NextPlot','new', ...
    'units','points',...
    'Visible','off', ...
    'Position',[ wex+200 wey-200 450 250]);
axis off

% creates a dialog box to input grid parameters
%
freq_field  =uicontrol('Style','edit',...
    'Position',[.60 .50 .22 .10],...
    'Units','normalized','String',num2str(step),...
    'Callback','step=str2double(get(freq_field,''String'')); set(freq_field,''String'',num2str(step));');

freq_field2=uicontrol('Style','edit',...
    'Position',[.60 .40 .22 .10],...
    'Units','normalized','String',num2str(dx),...
    'Callback','iwl2=str2double(get(freq_field2,''String'')); set(freq_field2,''String'',num2str(iwl2));');

uicontrol('Units','normal',...
    'Position',[.1 .70 .20 .12] ,'String','Load Alarm',...
     'Callback','close;loadala')


close_button=uicontrol('Style','Pushbutton',...
    'Position',[.80 .05 .15 .12 ],...
    'Units','normalized','Callback','close;done','String','Cancel');

go_button1=uicontrol('Style','Pushbutton',...
    'Position',[.10 .05 .35 .12 ],...
    'Units','normalized',...
    'Callback','close;  sta = ''rub'';allhist',...
    'String','Rubberband');

go_button2=uicontrol('Style','Pushbutton',...
    'Position',[.50 .05 .15 .12 ],...
    'Units','normalized',...
    'Callback','close;sta = ''lta'';allhist',...
    'String','LTA');


txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.30 0.84 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.l ,...
    'Color','r' ,...
    'FontWeight','bold',...
    'String',' Alarm Cube Parameters ');


txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.42 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.m ,...
    'FontWeight','bold',...
    'String','Time length of iwl in years');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.20 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.m ,...
    'FontWeight','bold',...
    'String','Select one of the statistics below ');

txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0. 0.53 0 ],...
    'Rotation',0 ,...
    'FontSize',fontsz.m,...
    'FontWeight','bold',...
    'String','Step width (Integer): ');


set(gcf,'visible','on');
watchoff
