%  This subroutine "indata.m" is the input parameter window
%  for circle
%

report_this_filefun(mfilename('fullpath'));

% initial values
%
ni = 100;

%
% make the interface
%
figure, clf reset
set(gcf,'visible','off');
set(gcf,'Units','normalized','NumberTitle','off','Name','Input Parameters');
set(gca,'visible','off');
set(gcf,'pos',[ 0.03    0.9 0.4 0.2])



freq_field=uicontrol('Style','edit',...
    'Position',[.60 .50 .22 .10],...
    'Units','normalized','String',num2str(ni),...
    'Callback','ni=str2double(get(freq_field,''String'')); set(freq_field,''String'',num2str(ni));');


close_button=uicontrol('Style','Pushbutton',...
    'Position',[.65 .10 .15 .15 ],...
    'Units','normalized','Callback','close','String','cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.35 .10 .15 .15 ],...
    'Units','normalized',...
    'Callback',' gocircle',...
    'String','Go');


txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.15 0.94 0 ],...
    'Rotation',0 ,...
    'FontSize',22 ,...
    'String',' Circle Parameters');


txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.1 0.55 0 ],...
    'Rotation',0 ,...
    'FontSize',16 ,...
    'String','Number of Events Ni:');

set(gcf,'visible','on');


