function inmisfit() % autogenerated function wrapper
    %
    % make dialog interface for misfit calculation
    %
    % S. Wiemer/Zhong Lu/Alex Allmann
    % turned into function by Celso G Reyes 2017
    
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    %
    report_this_filefun(mfilename('fullpath'));
    
    %if isunix ~= 1
    %  errordlg('Misfit laculation only implemented for UNIX version, sorry');
    %  return
    %end
    
    ZG.newcat = ZG.primeCatalog;
    
    %{
    if size(a(1,:)) < 12
        errordlg('You need 12 columns of Input Data to calculate misfit!');
        return
    end
    %}
    
    sig = 1;
    az = 180.;
    plu = 35.;
    R = 0.5;
    phi = 16;
    
    %{
    %initial values
    figure
    clf
    set(gca,'visible','off')
    set(gcf,'Units','pixel','NumberTitle','off','Name','Input Parameters for Misfit Calculation');
    
    set(gcf,'pos',[ ZG.welcome_pos ZG.welx+100 ZG.wely+50])
    %}
    bev=find(ZG.newcat.Magnitude==max(ZG.newcat.Magnitude)); %biggest events in catalog
    
    
    %default values of input parameters
    %ldx=100; %for seislap
    %tlap=100; %for seislap
    latt=ZG.newcat.Latitude(bev(1));
    longt=ZG.newcat.Longitude(bev(1));
    binlength=1;
    Mmin=3;
    ldepth=ZG.newcat.Depth(bev(1));
    
    % creates a dialog box to input some parameters
    
    zdlg = ZmapDialog([]);
    sigChoices = {'1','3'};
    sigDefault = strcmp(string(sig),sigChoices);
    zdlg.AddBasicPopup('sig','Choose Sigma',sigChoices,find(sigDefault),'Choose Sigma');
    zdlg.AddBasicEdit('plu','Plunge',plu,'Choose plunge');
    zdlg.AddBasicEdit('az','Azimuth',az,'Choose Azimuth');
    zdlg.AddBasicEdit('r','R value',R,'R-value');
    zdlg.AddBasicEdit('phi','Phi',phi,'Phi');
    zdlg.AddBasicCheckbox('doComparative','Compare misfits of different stress models',false,[],...
        'add this model to list of existing models, and then plot them all');
    [res,okPressed]=zdlg.Create('Misfit Calculation Parameters');
    if ~okPressed,return,end
    
    res.sig = str2double(sigChoices{res.sig});
    sig=res.sig;
    plu=res.plu;
    az=res.az;
    R=res.r;
    phi=res.phi;
    
    if doComparative
        compMisfit(mi2);
    end
    
    domisfit;
    
    %{
    txt1 = text('Units','normalized',...
        'Position',[0. 0.96 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Sigma 1 or 3? : ');
    
    
    txt2 = text('Units','normalized',...
        'Position',[0. 0.81 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input Plunge ');
    
    
    txt3 = text('Units','normalized',...
        'Position',[0. 0.66 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Please input Azimuth :');
    
    txt4 = text('Units','normalized',...
        'Position',[0. 0.51 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','R value:');
    txt5 = text('Units','normalized',...
        'Position',[0. 0.36 0 ],...
        'FontWeight','bold',...
        'FontSize',ZmapGlobal.Data.fontsz.m ,...
        'String','Phi :');
    %
    
    inp1_field  = uicontrol('Style','edit','Units','normalized',...
        'Position',[.85 .87 .13 .08],...
        'String',num2str(sig),...
        'callback',@cb_n_sigma);
    
    
    
    inp2_field  = uicontrol('Style','edit','Units','normalized',...
        'Position',[.85 .75 .13 .08],...
        'String',num2str(plu),...
        'callback',@cb_plunge);
    
    
    inp3_field=uicontrol('Style','edit','Units','normalized',...
        'Position',[.85 .63 .13 .08],...
        'String',num2str(az),...
        'callback',@cb_az);
    
    inp4_field=uicontrol('Style','edit','Units','normalized',...
        'Position',[.85 .51 .13 .08],...
        'String',num2str(R),...
        'callback',@cb_r);
    
    
    inp5_field=uicontrol('Style','edit','Units','normalized',...
        'Position',[.85 .39 .13 .08],...
        'String',num2str(phi),...
        'callback',@cb_phi);
    %
    close_button=uicontrol('Style','Pushbutton','Units','normalized',...
        'Position', [.72 .05 .15 .12 ],...
        'callback',@cb_cancel,'String','Cancel');
    
    inflap_button=uicontrol('Style','Pushbutton','Units','normalized',...
        'Position', [.49 .05 .15 .12 ],...
        'callback',@cb_info,'String','Info');
    
    compare_button=uicontrol('Style','Pushbutton','Units','normalized',...
        'Position', [.27 .05 .15 .12 ],...
        'callback',@cb_compmod,'String','CompMod');
    
    go_button=uicontrol('Style','Pushbutton','Units','normalized',...
        'Position',[.05 .05 .15 .12 ],...
        'callback',@cb_go,...
        'String','Go');
    
    set(gcf,'visible','on');watchoff
    
    function cb_n_sigma(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        sig=str2double(inp1_field.String);
        inp1_field.String=num2str(sig);
    end
    
    function cb_plunge(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        plu=str2double(inp2_field.String);
        inp2_field.String=num2str(plu);
    end
    
    function cb_az(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        az=str2double(inp3_field.String);
        inp3_field.String=num2str(az);
    end
    
    function cb_r(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        R=str2double(inp4_field.String);
        inp4_field.String=num2str(R);
    end
    
    function cb_phi(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        phi=str2double(inp5_field.String);
        inp5_field.String=num2str(phi);
    end
    
    function cb_cancel(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        close;
        ZmapMessageCenter();
    end
    
    function cb_info(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        infoz(1);
    end
    
    function cb_compmod(mysrc,myevt)
        % Compare Misfits of Different Stress Models
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        compMisfit;
    end
    
    function cb_go(mysrc,myevt)

        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        close;
        ZmapMessageCenter();
        domisfit;
    end
    
    %}
end
