function inpu2()
    %  This scriptfile ask for several selection parameters that can be set
    %  for part of the analysis. The original input parameters can be reset using
    %  the  Reset button in the main figure map
    %
    %
    % make the interface
    %
    global newt2
    report_this_filefun(mfilename('fullpath'));
    newt2 = catalog_overview(newt2);
end
%{
h=zmap_message_center();
message_window_candidates = findobj('Name','Message Window');

mess = max([message_window_candidates.Number]);
clear message_window_candidates
if isempty(mess) == 1; mess = 1 ; end
figure_w_normalized_uicontrolunits(mess)

mint = min(newt2.Date);
maxt = max(newt2.Date);
clf
set(gca,'visible','off');
set(gcf,'Units','pixel','pos',[20 fipo(4)-350 400 300])
set(gcf,'Name','Selection Parameters');

inp5t=uicontrol('Style','edit','Position',[.70 .70 .22 .06],...
    'Units','normalized','String',char(min(newt2.Date)),...
    'Callback','mint=str2double(get(inp5t,''String'')); set(inp5t,''String'',num2str(mint,6));');

inp6t=uicontrol('Style','edit','Position',[.70 .60 .22 .06],...
    'Units','normalized','String',char(max(newt2.Date)),...
    'Callback','maxt=str2double(get(inp6t,''String'')); set(inp6t,''String'',num2str(maxt,6));');

inp5=uicontrol('Style','edit','Position',[.70 .50 .22 .06],...
    'Units','normalized','String',num2str(minma2),...
    'Callback','minma2=str2double(get(inp5,''String'')); set(inp5,''String'',num2str(minma2));');

inp6=uicontrol('Style','edit','Position',[.70 .40 .22 .06],...
    'Units','normalized','String',num2str(maxma2),...
    'Callback','maxma2=str2double(get(inp6,''String'')); set(inp6,''String'',num2str(maxma2));');

inp7=uicontrol('Style','edit','Position',[.30 .20 .10 .06],...
    'Units','normalized','String',num2str(minde),...
    'Callback','minde=str2double(get(inp7,''String'')); set(inp7,''String'',num2str(minde));');

inp8=uicontrol('Style','edit','Position',[.60 .20 .10 .06],...
    'Units','normalized','String',num2str(maxde),...
    'Callback','maxde=str2double(get(inp8,''String'')); set(inp8,''String'',num2str(maxde));');



close_button=uicontrol('Style','Pushbutton',...
    'Position',[.65 .02 .20 .10 ],...
    'Units','normalized','Callback','welcome','String','cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.35 .02 .20 .10 ],...
    'Units','normalized',...
    'Callback','welcome, magcumu',...
    'String','Go');


txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.76 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.s ,...
    'FontWeight','bold',...
    'String','Minimum Time: ');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.64 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.s ,...
    'FontWeight','bold',...
    'String','Maximum Time: ');


txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.15 0.98 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold',...
    'String','Cut the catalog');


txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.52 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.s ,...
    'FontWeight','bold',...
    'String','Minimum Magnitude: ');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.39 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.s ,...
    'FontWeight','bold',...
    'String','Maximum Magnitude: ');

txt7 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.22 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.s ,...
    'FontWeight','bold',...
    'String','                 Min Depth                    Max Depth   ');


set(gcf,'visible','on')
%}


