%  This scriptfile ask for several input parameters that can be setup
%  at the beginning of each session. The default values are the
%  extrema in the catalog
%
%a = org;        % resets the main catalogue "a" to initial state
report_this_filefun(mfilename('fullpath'));

%  default values
t0b = min(a.Date);
teb = max(a.Date);
tdiff = (teb - t0b)*365;

% if two mainshocks arte define, use one only ..
if maepi.Count > 1 ; 
    maepi = maepi.subset(1) ;
end
% define maepi if not exist
l = find(newt2.Magnitude == max(newt2.Magnitude));
if ~exist('maepi') ; 
    maepi = newt2.subset(l);
end
if isempty('maepi') ; 
    maepi = newt2.subset(l);
end


%
% make the interface
%
figure_w_normalized_uicontrolunits(...
    'Units','pixel','pos',[300 100 300 400 ],...
    'Name','Define Mainshock Parameters!',...
    'visible','off',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Color',color_fbg,...
    'NextPlot','new');
axis off

inp1B=uicontrol('Style','edit','Position',[.70 .90 .22 .05],...
    'Units','normalized','String',num2str(floor(maepi(1,3))),...
    'Callback','maepi(1,3)=str2double(get(inp1B,''String'')); set(inp1B,''String'',num2str(floor(maepi(1,3))));');

inp1=uicontrol('Style','edit','Position',[.70 .80 .22 .05],...
    'Units','normalized','String',num2str(maepi(1,4)),...
    'Callback','maepi(1,4))=str2double(get(inp1,''String'')); set(inp1,''String'',num2str(maepi(1,4)))');

inp2=uicontrol('Style','edit','Position',[.70 .70 .22 .05],...
    'Units','normalized','String',num2str(maepi(1,5)),...
    'Callback','maepi(1,5)=str2double(get(inp2,''String'')); set(inp2,''String'',num2str(maepi(1,5)));');

inp3=uicontrol('Style','edit','Position',[.70 .60 .22 .05],...
    'Units','normalized','String',num2str(maepi(1,8)),...
    'Callback','maepi(1,8)=str2double(get(inp3,''String'')); set(inp3,''String'',num2str(maepi(1,8)));');


inp4=uicontrol('Style','edit','Position',[.70 .50 .22 .05],...
    'Units','normalized','String',num2str(maepi(1,9)),...
    'Callback','maepi(1,9)=str2double(get(inp4,''String'')); set(inp4,''String'',num2str(maepi(1,9)));');

inp5=uicontrol('Style','edit','Position',[.70 .40 .22 .05],...
    'Units','normalized','String',num2str(maepi(:,6)),...
    'Callback','maepi(:,6)=str2double(get(inp5,''String'')); set(inp5,''String'',num2str(maepi(:,6)));');

% inp6=uicontrol('Style','edit','Position',[.70 .30 .22 .05],...
%     'Units','normalized','String',num2str(maepi(:,7)),...
%     'Callback','maepi(:,7)=str2double(get(inp6,''String'')); set(inp6,''String'',num2str(maepi(:,7)));');

%   inp7=uicontrol('Style','edit','Position',[.20 .15 .25 .05],...
%       'Units','normalized','String',num2str(maepi(:,1)),...
%      'Callback','maepi(:,1)=str2double(get(inp7,''String'')); set(inp7,''String'',num2str(maepi(:,1)));');

% inp8=uicontrol('Style','edit','Position',[.60 .15 .25 .05],...
%     'Units','normalized','String',num2str(maepi(:,2)),...
%     'Callback','maepi(:,2)=str2double(get(inp8,''String'')); set(inp8,''String'',num2str(maepi(:,2));');



close_button=uicontrol('Style','Pushbutton',...
    'Position',[.65 .02 .20 .10 ],...
    'Units','normalized','Callback','close;zmap_message_center.set_info('' '','' '');done','String','cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.35 .02 .20 .10 ],...
    'Units','normalized',...
    'Callback','close,think, pvalcat',...
    'String','Go');

info_button=uicontrol('Style','Pushbutton',...
    'Position',[.05 .02 .20 .10 ],...
    'Units','normalized',...
    'Callback','zmaphelp(titstr,hlpStr)',...
    'String','Info');
titstr = 'General Parameters';
hlpStr = ...
    ['This window allows you to enyter the         '
    'mainshock magnitude and time etc.            '
    'time, magnitude and depth.                   '
    '                                             '];




txt3 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 1.00 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Year');


txt1 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.75 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Day');

txt2 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.87 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Month');

txt4 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.63 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Hour');

txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.51 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Minute');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.38 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Magnitude ');


%clear txt1 txt2 txt3 txt4 txt5 txt6 txt7 inp1 inp1B inp3 inp3 inp4 inp5 inp6 inp7
set(gcf,'visible','on')
watchoff
str = [ 'Please Select a subset of earthquakes'
    ' and press Go                        '];
zmap_message_center.set_message('Message',str);


