function [Mc, Mc90, Mc95, magco, prf]= mcperc_ca3() % autogenerated function wrapper
    % turned into function by Celso G Reyes 2017
    % returns:
    %     [Mc, Mc90, Mc95, magco, prf]
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    % This is a comleteness determination test
    
    [bval,xt2] = histcounts(ZG.newt2.Magnitude,-2:0.1:6);
    l = find(bval == max(bval), 1, 'last' );
    magco0 =  xt2(l);
    
    loopvalues=magco0-0.5:0.1:magco0+0.7;
    dat=nan(numel(loopvalues),2);
    
    %for i = magco0-0.6:0.1:magco0+0.2
    n=0;
    for i = loopvalues
        n=n+1;
        l = ZG.newt2.Magnitude >= i - 0.0499;
        if sum(l) >= 25
            %[bv magco stan,  av] =  bvalca3(ZG.newt2.subset(l),2);
            [mw, bv2, stan2, av] =  bmemag(ZG.newt2.subset(l));
            try %in case something goes wrong
                res2=synthb_aut(bv2,i,l);
            catch ME
                warning(ME.message);
                res2=nan;
            end
            dat(n,:) = [i, res2];
        else
            dat(n,:) = [i NaN];
        end
        
    end
    
    j =  find(dat(:,2) < 10 , 1 );
    if isempty(j)
        Mc90 = NaN ;
    else
        Mc90 = dat(j,1);
    end
    
    j =  find(dat(:,2) < 5 , 1 );
    if isempty(j) 
        Mc95 = NaN ;
    else
        Mc95 = dat(j,1);
    end
    
    j =  find(dat(:,2) < 10 , 1 );
    if isempty(j); j =  find(dat(:,2) < 15 , 1 ); end
    if isempty(j); j =  find(dat(:,2) < 20 , 1 ); end
    if isempty(j); j =  find(dat(:,2) < 25 , 1 ); end
    j2 =  find(dat(:,2) == min(dat(:,2)) , 1 );
    %j = min([j j2]);
    
    Mc = dat(j,1);
    magco = Mc;
    prf = 100 - dat(j2,2);
    if isempty(magco)
        magco = NaN;
        prf = 100 -min(dat(:,2));
    end
    %disp(['Completeness Mc: ' num2str(Mc) ]);
    
    
    
end
