function mcwtidays() % autogenerated function wrapper
    % turned into function by Celso G Reyes 2017
    
    report_this_filefun(mfilename('fullpath'));
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    bv2 = [];
    bv3 = [] ;
    me = [];
    def = {'150'};
    ni2 = inputdlg('Number of events in each window?','Input',1,def);
    l = ni2{:};
    ni = str2double(l);
    BV = [];
    
    
    itervector=1:ni/5:ZG.newt2.Count - ni;
    % expect trouble elsewhere if bv2 or BV are reused... they've changed from matrices to structs
    % to handle dates better.
    bv2=struct(...
        'magco',nan(numel(itervector),1),...
        'date',NaT(numel(itervector),1) );
    bV=struct(...
        'magco',nan(numel(itervector)*3,1),... was inf!
        'date',NaT(numel(itervector)*3,1));
    
    %bv2=nan(numel(itervector),2);
    %BV= nan(numel(itervector)*3,2);
    for n = 1:numel(itervector)
        i=itervector(n);
        [~, magco, ~ ] =  bvalca2(ZG.newt2.subset(i:i+ni));
        bv2.magco(n) = magco;
        bv2.date(n) = ZG.newt2.Date(i+ni/2);
        BV.magco(n*3-2:n*3-1) = magco;
        BV.date(n*3-2 : n*3-1) = [ZG.newt2.Date(i); ZG.newt2.Date(i+ni)];
        
    end
    
    % Find out if figure already exists
    %
    Mcfig=findobj('Type','Figure','-and','Name','Mc with time');
    
    % Set up the window
    
    if isempty(Mcfig)
        Mcfig = figure_w_normalized_uicontrolunits( ...
            'Name','Mc with time',...
            'NumberTitle','off', ...
            'NextPlot','replace', ...
            'backingstore','on',...
            'Visible','on');
        
        
    end
    figure(Mcfig);
    %TODO instead of completely recreating plots, just edit the existing ones
    delete(findobj(Mcfig,'Type','axes'));
    axis off
    
    i  = find(ZG.newt2.Magnitude ==  max(ZG.newt2.Magnitude), 1 );
    ZG.maepi = ZG.newt2.subset(i); % guaranteed to be only one event
    
    rect = [0.15 0.30 0.7 0.45];
    axes('position',rect)
    pl = plot(days(bv2.date-ZG.maepi.Date),bv2.magco,'^r');
    set(pl,'LineWidth',1.5,'MarkerSize',10,...
        'MarkerFaceColor','y','MarkerEdgeColor','r')
    hold on
    pl = plot(days(bv2.date-ZG.maepi.Date),bv2.magco,'b');
    set(pl,'LineWidth',1.0)
    pl = plot(days(BV.date-ZG.maepi.Date),BV.magco,'color',[0.5 0.5 0.5]);
    
    %grid
    set(gca,'Color',ZG.color_bg)
    set(gca,'box','on',...
        'SortMethod','childorder','TickDir','out','FontWeight',...
        'bold','FontSize',ZmapGlobal.Data.fontsz.m,'Linewidth',1.2)
    %
    ylabel('Mc')
    %set(gca,'Xlim',[t0b teb]);
    
    xlabel('Time in days after mainshock')
    tist = [  ZG.newt2.Name ' - b(t), ni = ' num2str(ni) ];
    title(tist,'interpreter','none')
    
    
    
    %% what is the purpose of following code?
    
    
    nt = [];
    con = 0;
    
    ms = round(bv2.magco,1);
    for  m = max(bv2.magco):-0.1:min(bv2.magco)
        
        % find comp level and times.
        i = find(abs(m-ms) < 0.01, 1, 'last' );
        if ~isempty(i)
            con = con+1;
            nt = [nt ; m decyear(bv2.date(i))];
            
            if con > 1 &&  nt(con,2) < nt(con-1,2)
                nt(con,:) = []; 
                con = con-1; 
            end
        end
    end
    
    nt(1,2) = min(decyear(ZG.newt2.Date));
    i = find((ms-min(ms) > 0.01), 1, 'last' );
    % nt(con,2) = bv2(i+1,2);
    
    
    
    
end
