function morel() % autogenerated function wrapper
    % this script will plot the cumulative moment
    % release as a function of time
    % turned into function by Celso G Reyes 2017
    
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    %  Stefan Wiemer  2/95
    
    report_this_filefun(mfilename('fullpath'));
    
    figure
    set(gcf,'PaperPosition',[2 1 5.5 7.5])
    
    
    
    %  Do the calculation
    c = cumsum( 10.^(1.5*ZG.newt2.Magnitude + 16.1));
    
    
    pl = plot(ZG.newt2.Date,c)
    set(pl,'LineWidth',2.0)
    xlabel('Time in years ','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m)
    ylabel('Cumulative Moment ','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m)
    
    %te = text(0.1,0.9,'log10(Mo) = 1.5Ms + 16.1;','Units','normalized','FontWeight','bold')
    
    set(gca,'visible','on','FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','bold',...
        'FontWeight','bold','LineWidth',1.5,...
        'Box','on')
    
    hold on
    grid
    
    
    
end
