function nlammap() % autogenerated function wrapper
    %  lammap displays a map view of the seismicity in Lambert projection and ask for two input
    % points select with the cursor. These input points are
    % the endpoints of the crossection.
    %
    % Stefan Wiemer 2/95
    % last update: 12.10.2004, jochen.woessner@sed.ethz.ch
    % turned into function by Celso G Reyes 2017
    
    %global a
    %global main mainfault faults coastline vo s1 s2 s3 s4
    %global mapl fipo
    %global h2 xsec_fig newa lat1 leng lon1 lon2 lat2
    
    %{
%% This is how you do it with the mapping toolbox -CGR
fig = figure;
axm=axesm(fig,'lambert','MapLatLimit',[min(ZG.primeCatalog.Latitude) max(ZG.primeCatalog.Latitude)],'MapLonLimit',[min(ZG.primeCatalog.Longitude) max(ZG.primeCatalog.Longitude)]);
plm=plotm(coastlat,coastlon,'k');
plm=plotm(ZG.primeCatalog.Latitude,ZG.primeCatalog.Longitude,'.');
disp('Select one end of cross-section')
p1=ginput(1); %TODO offer chance to redo/abort

disp('Select other end of cross-section')
p2=ginput(1);

    %}
    ZG=ZmapGlobal.Data;
    report_this_filefun(mfilename('fullpath'));
    %
    % Find out if figure already exists
    %
    mapl=findobj('Type','Figure','-and','Name','Seismicity Map (Lambert)');
    
    
    ZG.xsec_rotation_deg = 0;
    % Set up the Seismicity Map window Enviroment
    %
    if isempty(mapl)
        mapl = figure_w_normalized_uicontrolunits( ...
            'Name','Seismicity Map (Lambert)',...
            'NumberTitle','off', ...
            'backingstore','on',...
            'Visible','off', ...
            'Position',[ (ZG.fipo(3:4) - [600 400]) ZmapGlobal.Data.map_len]);
        
        
        drawnow
        
        uicontrol('Units','normal',...
            'Position',[.0 .93 .08 .06],'String','Info ',...
            'callback',@info1_callback);
        
        
        uicontrol('Units','normal',...
            'Position',[.0 .93 .08 .06],'String','Info ',...
            'callback',@info2_callback);
        
        
    end % if figure exist
    
    figure(mapl);
    delete(findobj(mapl,'Type','axes'));
        if isempty(coastline)
            coastline = [ZG.primeCatalog.Longitude(1) ZG.primeCatalog.Latitude(1)];
        end
        hold on
        % Added try-catch to prevent failure if no coastline is inside
        % cross-section box, JW
        %try
        if length(coastline) > 1 %TODO what is coastline?
            lc_map(coastline(:,2),coastline(:,1),s3,s4,s1,s2)
            g = get(gca,'Children');
            set(g,'Color','k')
            
            %catch
        end
        hold on
        try
            if length(faults) > 10
                lc_map(faults(:,2),faults(:,1),s3,s4,s1,s2)
            end
        catch
        end
        hold on
        if ~isempty(mainfault)
            lc_map(mainfault(:,2),mainfault(:,1),s3,s4,s1,s2)
        end
        
        at_dep1 = ZG.primeCatalog.Depth<=dep1;
        at_dep2 = ZG.primeCatalog.Depth<=dep2 & ZG.primeCatalog.Depth>dep1;
        at_dep3 = ZG.primeCatalog.Depth<=dep3 & ZG.primeCatalog.Depth>dep2;
        if ZG.primeCatalog.Count > 5000
            %lc_event(ZG.primeCatalog.Latitude,ZG.primeCatalog.Longitude,'.k')
            lc_event(ZG.primeCatalog.Latitude(at_dep1),ZG.primeCatalog.Longitude(at_dep1),'.b',1);
            lc_event(ZG.primeCatalog.Latitude(at_dep2),ZG.primeCatalog.Longitude(at_dep2),'.g',1);
            lc_event(ZG.primeCatalog.Latitude(at_dep3),ZG.primeCatalog.Longitude(at_dep3),'.r',1);
        else
            lc_event(ZG.primeCatalog.Latitude(at_dep1),ZG.primeCatalog.Longitude(at_dep1),'+b');
            lc_event(ZG.primeCatalog.Latitude(at_dep2),ZG.primeCatalog.Longitude(at_dep2),'og');
            lc_event(ZG.primeCatalog.Latitude(at_dep3),ZG.primeCatalog.Longitude(at_dep3),'xr');
            
        end
        
        if ~isempty(ZG.maepi)
            lc_event(ZG.maepi.Latitude,ZG.maepi.Longitude,'hy',10,2.0)
        end
        if ~isempty(main)
            lc_event(main(:,2),main(:,1),'hk',10,2.0)
        end
        if ~isempty(vo)
            lc_event(vo.Latitude,vo.Longitude,'^r')
        end
        if ~isempty(well)
            lc_event(well(:,2),well(:,1),'dk')
        end
    
    labelList={'Select an option',...
        'Select Endpoints by Mouse',...
        'Coordinate Input',...
        'Multiple segments',...
        'Rotate X-Section'};
    labelPos = [.05 .00 .40 .06];
    
    tmp1=ZG.primeCatalog.Latitude';
    tmp2=ZG.primeCatalog.Longitude';
    
    uic = uicontrol(...
        'Style','popup',...
        'Units','normalized',...
        'Position',labelPos,...
        'String',labelList,...
        'Backgroundcolor',[0.9 0.9 0.9],...
        'callback', @select_xsection);
    
    
    set_width = uicontrol('style','edit','value',ZG.xsec_width_km,...
        'string',num2str(ZG.xsec_width_km), 'background',[0.9 0.9 0.9],...
        'units','norm','pos',[.90 .00 .08 .06],'min',0,'max',10000,...
        'callback',@select_xc_width);
    
    uicontrol('style','text','units','norm',...
        'Backgroundcolor',[0.9 0.9 0.9],...
        'pos',[.70 .00 .20 .06]);
    set(wilabel,'string','Width in km:');
    
    uicontrol('style','edit','value',ZG.xsec_rotation_deg,...
        'string',num2str(ZG.xsec_rotation_deg), 'background',[0.9 0.9 0.9],...
        'units','norm','pos',[.60 .00 .08 .06],'min',0,'max',360,...
        'callback',@callbackfun_005);
    
    uicontrol('style','text','units','norm',...
        'Backgroundcolor',[0.9 0.9 0.9],...
        'pos',[.50 .00 .10 .06], 'string', 'Angle [deg]:');
    
    
    
    function info1_callback(mysrc,myevt)
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        web(['file:' ZG.hodi '/zmapwww/chp11.htm#996756']) ;
    end
    
    function info2_callback(mysrc,myevt)
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        web(['file:' ZG.hodi '/zmapwww/chap4.htm#997433']) ;
    end
    
    function select_xsection(mysrc,myevt)
        callback_tracker(mysrc,myevt,mfilename('fullpath'));
        in2=uic.Value;
        switch in2
            case 2
                [xsecx xsecy,  inde] = mysect(tmp1,tmp2,ZG.primeCatalog.Depth,ZG.xsec_width_km);
                nlammap2; %select endpoints by mouse
            case 3
                posinpu; % coordinate input
            case 4
                musec; % multiple segments
            case 5
                rotateit; % rotate cross-section
            otherwise
                error('unknown option');
        end
    end
    
    function select_xc_width(mysrc,myevt)
        ZG.xsec_width_km=str2double(mysrc.String);
    end
    
    function callbackfun_005(mysrc,myevt)
        ZG.xsec_rotation_deg=str2double(mysrc.String);
    end
    
end
