%  This scriptfile ask for several input parameters that can be setup
%  at the beginning of each session. The default values are the
%  extrema in the catalog
%
%a = org;        % resets the main catalogue "a" to initial state
report_this_filefun(mfilename('fullpath'));

%
% make the interface

%
figure_w_normalized_uicontrolunits(...
    'Units','pixel','pos',[ZG.welcome_pos 380 500 ],...
    'Name','Pre-selection Parameters!',...
    'visible','off',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Color',color_fbg,...
    'NextPlot','new');
axis off

inp1A=uicontrol('Style','edit','Position',[.30 .80 .15 .05],...
    'Units','normalized','String',num2str(latmin,6),...
    'Callback','latmin=str2double(inp1A.String); inp1A.String=num2str(latmin,6))');

inp2A=uicontrol('Style','edit','Position',[.30 .70 .15 .05],...
    'Units','normalized','String',num2str(latmax,6),...
    'Callback','latmax=str2double(inp2A.String); inp2A.String=num2str(latmax,6);');

inp1=uicontrol('Style','edit','Position',[.70 .80 .15 .05],...
    'Units','normalized','String',num2str(lonmin,6),...
    'Callback','lonmin=str2double(inp1.String); inp1.String=num2str(lonmin,6))');

inp2=uicontrol('Style','edit','Position',[.70 .70 .15 .05],...
    'Units','normalized','String',num2str(lonmax,6),...
    'Callback','lonmax=str2double(inp2.String); inp2.String=num2str(lonmax,6);');

inp3=uicontrol('Style','edit','Position',[.70 .60 .22 .05],...
    'Units','normalized','String',num2str(tmin),...
    'Callback','tmin=str2double(inp3.String); inp3.String=num2str(tmin);');

inp4=uicontrol('Style','edit','Position',[.70 .50 .22 .05],...
    'Units','normalized','String',num2str(tmax),...
    'Callback','tmax=str2double(inp4.String); inp4.String=num2str(tmax);');

inp5=uicontrol('Style','edit','Position',[.70 .40 .22 .05],...
    'Units','normalized','String',num2str(Mmin),...
    'Callback','Mmin=str2double(inp5.String); inp5.String=num2str(Mmin);');

inp6=uicontrol('Style','edit','Position',[.70 .30 .22 .05],...
    'Units','normalized','String',num2str(Mmax),...
    'Callback','Mmax=str2double(inp6.String); inp6.String=num2str(Mmax);');

inp7=uicontrol('Style','edit','Position',[.30 .15 .15 .05],...
    'Units','normalized','String',num2str(mindep),...
    'Callback','mindep=str2double(inp7.String); inp7.String=num2str(mindep);');

inp8=uicontrol('Style','edit','Position',[.50 .15 .15 .05],...
    'Units','normalized','String',num2str(maxdep),...
    'Callback','maxdep=str2double(inp8.String); inp8.String=num2str(maxdep);');



close_button=uicontrol('Style','Pushbutton',...
    'Position',[.65 .02 .20 .10 ],...
    'Units','normalized','Callback','close;zmap_message_center.set_info('' '','' '');done','String','cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.35 .02 .20 .10 ],...
    'Units','normalized',...
    'Callback','close,think, inda = 2 ; eval(call);',...
    'String','Go');

info_button=uicontrol('Style','Pushbutton',...
    'Position',[.05 .02 .20 .10 ],...
    'Units','normalized',...
    'Callback','zmaphelp(titstr,hlpStr)',...
    'String','Info');
titstr = 'General Parameters';
hlpStr = ...
    ['This window allows you to select earthquakes '
    'from a catalog. You can select a subset in   '
    'time, magnitude and depth.                   '
    '                                             '
    'The top frame displays the number of         '
    'earthquakes in the catalog - no selection is '
    'possible.                                    '
    '                                             '
    'Two more parameters can be adjusted: The Bin '
    'length in days that is used to sample the    '
    'seismicity and the minimum magnitude of      '
    'quakes displayed with a larger symbol in the '
    'map.                                         '];




text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.55 0.75 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','max Lon:');

text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.55 0.87 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','min Lon: ');


text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.75 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','max Lat:');

text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.87 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','min Lat: ');

txt4 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.63 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Beginning year: ');

txt5 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.51 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Ending year: ');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.38 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Minimum Magnitude: ');

txt6 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.25 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','Maximum Magnitude: ');

txt7 = text(...
    'Color',[0 0 0 ],...
    'EraseMode','normal',...
    'Position',[0.02 0.15 0 ],...
    'Rotation',0 ,...
    'FontSize',ZmapGlobal.Data.fontsz.m ,...
    'FontWeight','bold' ,...
    'String','       Min Depth                Max Depth  ');


%clear txt1 txt2 txt3 txt4 txt5 txt6 txt7 inp1 inp1B inp3 inp3 inp4 inp5 inp6 inp7
set(gcf,'visible','on')
watchoff
str = [ 'Please Select a subset of earthquakes'
    ' and press Go                        '];
zmap_message_center.set_message('Message',str);


