report_this_filefun(mfilename('fullpath'));

ButtonName=questdlg('Really Quit?', ...
    'Warning', ...
    'Yes','Cancel','');

switch ButtonName
    case 'Yes'
        disp('Quitting ZMAP - have a nice day'); quitzmap;
    case 'Cancel'
        disp('Canceled'); return
end % switch


return


quitui = dialog('style','error', ...
    'units','pixels', ...
    'position',[400 300 200 100], ...
    'name','Question Dialog', ...
    'textstring','Really QUIT ?', ...
    'buttonstrings','Yes|Cancel', ...
    'backgroundcolor',[.8 .8 .8], ...
    'foregroundcolor',[0 0 0], ...
    'buttoncalls','disp(''Quiting ZMAP, have a nice day!''),delete(gcf),quit|delete(gcf)');

