function selco2()
    % This is the machine-generated representation of a MATLAB object
    % and its children.  Note that handle values may change when these
    % objects are re-created. This may cause problems with some callbacks.
    % The command syntax may be supported in the future, but is currently
    % incomplete and subject to change.
    %
    % To re-open this system, just type the name of the m-file at the MATLAB
    % prompt. The M-file and its associtated MAT-file must be on your path.

    report_this_filefun(mfilename('fullpath'));

    load selco2

    a = figure_w_normalized_uicontrolunits('Color',[0.9 0.9 0.9], ...
        'Colormap',mat0, ...
        'InvertHardcopy','off', ...
        'PointerShapeCData',mat1, ...
        'Position',[153 555 362 215], ...
        'Tag','Fig1');
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.752941 0.752941 0.752941], ...
        'Position',[57.1034 108 149.586 15.5172], ...
        'String','Select an option', ...
        'Style','text', ...
        'Tag','StaticText1');
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Callback','C = uisetcolor;cb1 = C(1);cb2=C(2);cb3=C(3);mainmap_overview()', ...
        'Position',[53.3793 70.1379 108 21.7241], ...
        'String','Graph Background', ...
        'Tag','Pushbutton1');
