
% make dialog interface for the fixing of the legend
%


%
report_this_filefun(mfilename('fullpath'));


%initial values
figure_w_normalized_uicontrolunits(mess)
clf
set(gca,'visible','off')
set(gcf,'Units','pixel','NumberTitle','off','Name','Input Parameters');

set(gcf,'pos',[ wex  wey welx+200 wely-50])


if typele =='tim'

    % creates a dialog box to input some parameters
    %
    tim1 = t0b;
    tim2 = t0b +  (teb-t0b)/3;
    tim3 = t0b +  (teb-t0b)*0.663;
    tim4 = teb;

    inp2_field  = uicontrol('Style','edit',...
        'Position',[.80 .800 .18 .15],...
        'Units','normalized','String',num2str(tim1),...
        'Callback','tim1=str2double(get(inp2_field,''String''));set(inp2_field,''String'',num2str(tim1));');

    txt2 = text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.9 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time 1:');


    txt3 = text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.70 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time2 :');

    text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.45 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time3 :');

    text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.25 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time4 :');



    inp3_field=uicontrol('Style','edit',...
        'Position',[.80 .630 .18 .15],...
        'Units','normalized','String',num2str(tim2),...
        'Callback','tim2=str2double(get(inp3_field,''String'')); set(inp3_field,''String'',num2str(tim2));');

    inp4_field=uicontrol('Style','edit',...
        'Position',[.80 .450 .18 .15],...
        'Units','normalized','String',num2str(tim3),...
        'Callback','tim3=str2double(get(inp4_field,''String'')); set(inp4_field,''String'',num2str(tim3));');

    inp5_field=uicontrol('Style','edit',...
        'Position',[.80 .250 .18 .15],...
        'Units','normalized','String',num2str(tim4),...
        'Callback','tim4=str2double(get(inp5_field,''String'')); set(inp5_field,''String'',num2str(tim4));');

end



close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','welcome','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','welcome;typele =''tim'';subcata',...
    'String','Go');

set(gcf,'visible','on');watchoff


