
% make dialog interface for the fixing of the legend
%


% TODO fix the way times are handled
report_this_filefun(mfilename('fullpath'));


%initial values
timeselect_dlg = figure_w_normalized_uicontrolunits('Menu','none','Tag','timeselect_dlg',...
    'Units','pixel','NumberTitle','off','Name','Choose TIME divisions','pos',[ wex  wey 200 250]);
timeselect_ax = axes('Visible','off');


if typele =='tim'

    % creates a dialog box to input some parameters
    %
    tim1 = t0b;
    tim2 = t0b +  (teb-t0b)/3;
    tim3 = t0b +  (teb-t0b)*0.663;
    tim4 = teb;

    tx_x = .05;
    fl_x = 0.5;
    fl_w = 0.4;
    inp2_field  = uicontrol(timeselect_dlg,'Style','edit',...
        'Position',[fl_x .800 fl_w .15],...
        'Units','normalized','String',num2str(tim1),...
        'Callback','tim1=str2double(get(inp2_field,''String''));set(inp2_field,''String'',num2str(tim1));');

    txt2 = text(timeselect_ax,...
        'Position',[tx_x 0.9],...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time 1:');


    txt3 = text(timeselect_ax,...
        'Position',[tx_x 0.70],...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time2 :');

    text(timeselect_ax,...
        'Position',[tx_x 0.45],...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time3 :');

    text(timeselect_ax,...
        'Position',[tx_x 0.25],...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Time4 :');



    inp3_field=uicontrol(timeselect_dlg,'Style','edit',...
        'Position',[fl_x .630 fl_w .15],...
        'Units','normalized','String',num2str(tim2),...
        'Callback','tim2=str2double(get(inp3_field,''String'')); set(inp3_field,''String'',num2str(tim2));');

    inp4_field=uicontrol(timeselect_dlg,'Style','edit',...
        'Position',[fl_x .450 fl_w .15],...
        'Units','normalized','String',num2str(tim3),...
        'Callback','tim3=str2double(get(inp4_field,''String'')); set(inp4_field,''String'',num2str(tim3));');

    inp5_field=uicontrol(timeselect_dlg,'Style','edit',...
        'Position',[fl_x .250 fl_w .15],...
        'Units','normalized','String',num2str(tim4),...
        'Callback','tim4=str2double(get(inp5_field,''String'')); set(inp5_field,''String'',num2str(tim4));');

end



close_button=uicontrol(timeselect_dlg,'Style','Pushbutton',...
    'Position', [.60 .05 .3 .15 ],...
    'Units','normalized','Callback','close(timeselect_dlg);welcome','String','Cancel');

go_button=uicontrol(timeselect_dlg,'Style','Pushbutton',...
    'Position',[.25 .05 .3 .15 ],...
    'Units','normalized',...
    'Callback','close(timeselect_dlg);welcome;typele =''tim'';mainmap_overview()',...
    'String','Go');

timeselect.dlg.Visible = 'on';
watchoff();


