
% make dialog interface for the fixing of the legend
%


%
report_this_filefun(mfilename('fullpath'));


%initial values
figure_w_normalized_uicontrolunits(mess)
clf
set(gca,'visible','off')
set(gcf,'Units','pixel','NumberTitle','off','Name','Input Parameters');

set(gcf,'pos',[ wex  wey welx+200 wely-50])


if typele =='mag'

    % creates a dialog box to input some parameters
    %
    dep3 = max(a(:,6));
    dep1 = min(a(:,6));
    dep2 = (dep1+dep3)*2/3;
    dep1 = (dep1+dep3)*1/3;

    inp2_field  = uicontrol('Style','edit',...
        'Position',[.80 .800 .18 .15],...
        'Units','normalized','String',num2str(dep1),...
        'Callback','dep1=str2double(get(inp2_field,''String''));set(inp2_field,''String'',num2str(dep1));');

    txt2 = text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.9 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Magnitude 1:');


    txt3 = text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.70 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Magnitude 2:');

    text(...
        'Color',[0 0 0 ],...
        'EraseMode','normal',...
        'Position',[0.5 0.45 0 ],...
        'Rotation',0 ,...
        'FontWeight','bold',...
        'FontSize',fontsz.m ,...
        'String','Magnitude 3:');


    inp3_field=uicontrol('Style','edit',...
        'Position',[.80 .630 .18 .15],...
        'Units','normalized','String',num2str(dep2),...
        'Callback','dep2=str2double(get(inp3_field,''String'')); set(inp3_field,''String'',num2str(dep2));');

    inp4_field=uicontrol('Style','edit',...
        'Position',[.80 .450 .18 .15],...
        'Units','normalized','String',num2str(dep3),...
        'Callback','dep3=str2double(get(inp4_field,''String'')); set(inp4_field,''String'',num2str(dep3));');

end



close_button=uicontrol('Style','Pushbutton',...
    'Position', [.60 .05 .15 .15 ],...
    'Units','normalized','Callback','welcome','String','Cancel');

go_button=uicontrol('Style','Pushbutton',...
    'Position',[.25 .05 .15 .15 ],...
    'Units','normalized',...
    'Callback','welcome;typele =''mag'';subcata',...
    'String','Go');

set(gcf,'visible','on');watchoff


