function res2=synthb_aut(bv2,i, l) % autogenerated function wrapper
    %This is synthetic219
    %This program generates a synthetic catalog of given total number of events, b-value, minimum magnitude,
    %and magnitude increment.
    %The synthetic catalog will be sotred in a file "synt.mat"
    % Yuzo Toya 2/1999
    % turned into function by Celso G Reyes 2017
    
    ZG=ZmapGlobal.Data; % used by get_zmap_globals
    
    %report_this_filefun(mfilename('fullpath'));
    
    TN = ZG.newt2.Count;  %total number of events
    B = bv2 ;%b-value
    IM= i;%starting magnitude (hypothetical Mc)
    inc = 0.1 ;%magnitude increment
    
    % log10(N)=A-B*M
    M=[IM:inc:15];
    N=10.^(log10(TN)-B*(M-IM));
    aval=(log10(TN)-B*(0-IM));
    N=round(N);
    %N=floor(N);
    %N=ceil(N);
    
    syn = nan(TN,9);
    new = nan(TN,1);
    
    %[ttt,indt]=sortrows(new,3);
    %new=ttt;
    %new=a
    ct1=1;
    
    
    ct1  = find(N == 0, 1 ) - 1;
    if isempty(ct1) ; ct1 = length(N); end
    
    ctM=M(ct1);
    count=0;
    ct=0;
    swt=0;
    sc=0;
    for I=IM:inc:ctM
        ct=ct+1;
        if I~=ctM
            for sc=1:(N(ct)-N(ct+1))
                count=count+1;
                new(count)=I;
            end
        else
            count=count+1;
            new(count)=I;
        end
    end
    
    
    PM=M(1:ct);
    PN=log10(N(1:ct));
    %bdiff(ZG.newt2)
    %ga = findobj('Tag','cufi');
    %axes(ga); hold on;
    %plot(PM,N(1:ct));
    %pause
    N = N(1:ct);
    %le = length(ZG.newt2(l,:));
    [bval,xt2] = hist(ZG.newt2.Magnitude(l),PM); % guessing l comes from caller
    b3 = fliplr(cumsum(fliplr(bval)));    % N for M >= (counted backwards)
    res2 = sum(abs(b3 - N))/sum(b3)*100;
    res = res2;
    
end
