function timcplo() % autogenerated function wrapper
%  tidpl  plots a time projection plot of the seismicity
%  Stefan Wiemer 5/95
%
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals
report_this_filefun(mfilename('fullpath'));


newcat = a;
xt2  = [ ];
meand = [ ];
er = [];
ind = 0;

% Find out of figure already exists
%
[existFlag,figNumber]=figure_exists('Time Distance',1);
newDepWindowFlag=~existFlag;

% Set up the Seismicity Map window Enviroment
%
if newDepWindowFlag

    figure_w_normalized_uicontrolunits(...
        'Name','Time Distance',...
        'visible','off',...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'NextPlot','new', ...
        'Units','Pixel',  'Position',[ZG.welcome_pos 550 400'])
    tifg = gcf;
    hold on
    axis off
    matdraw
    
    % Make the menu to change symbol size and type
    %
    symbolmenu = uimenu('Label',' Symbol ');
    SizeMenu = uimenu(symbolmenu,'Label',' Symbol Size ');
    TypeMenu = uimenu(symbolmenu,'Label',' Symbol Type ');
    uimenu(SizeMenu,'Label','3','callback',@callbackfun_001);
    uimenu(SizeMenu,'Label','6','callback',@callbackfun_002);
    uimenu(SizeMenu,'Label','9','callback',@callbackfun_003);
    uimenu(SizeMenu,'Label','12','callback',@callbackfun_004);
    uimenu(SizeMenu,'Label','14','callback',@callbackfun_005);
    uimenu(SizeMenu,'Label','18','callback',@callbackfun_006);
    uimenu(SizeMenu,'Label','24','callback',@callbackfun_007);

    uimenu(TypeMenu,'Label','dot',...
        'callback',@callbackfun_008);
    uimenu(TypeMenu,'Label','red+ blue o green x',...
        'callback',@callbackfun_009);
    uimenu(TypeMenu,'Label','o','Callback',...
        'ty1=''o'';ty2=''o'';ty3=''o'';eval(cal6)');
    uimenu(TypeMenu,'Label','x','Callback',...
        'ty1=''x'';ty2=''x'';ty3=''x'';eval(cal6)');
    uimenu(TypeMenu,'Label','*',...
        'callback',@callbackfun_010);
    uimenu(TypeMenu,'Label','none','callback',@callbackfun_011);
    cal6 = ...
        [ 'set(deplo1,''MarkerSize'',ZG.ms6,''LineStyle'',ty1,''visible'',''on'');',...
        'set(deplo2,''MarkerSize'',ZG.ms6,''LineStyle'',ty2,''visible'',''on'');',...
        'set(deplo3,''MarkerSize'',ZG.ms6,''LineStyle'',ty3,''visible'',''on'');' ];

end  % if figure exist

figure_w_normalized_uicontrolunits(tifg)

delete(gca);delete(gca);delete(gca);
set(gca,'visible','off');

orient tall
rect = [0.15, 0.15, 0.75, 0.65];
axes('position',rect)
p5 = gca;

n = length(newa(1,:));
deplo1 =plot(newa(newa(:,7)<=dep1,n),newa(newa(:,7)<=dep1,3),'.b');
set(deplo1,'MarkerSize',ZG.ms6,'Marker',ty1,'era','normal')
hold on
deplo2 =plot(newa(newa(:,7)<=dep2&newa(:,7)>dep1,n),newa(newa(:,7)<=dep2&newa(:,7)>dep1,3),'.g');
set(deplo2,'MarkerSize',ZG.ms6,'Marker',ty2,'era','normal');
deplo3 =plot(newa(newa(:,7)<=dep3&newa(:,7)>dep2,n),newa(newa(:,7)<=dep3&newa(:,7)>dep2,3),'.r');
set(deplo3,'MarkerSize',ZG.ms6,'Marker',ty3,'era','normal')

hold on

xlabel('Distance in [km] ','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m)
ylabel('Time  in years ','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m)

set(gca,'box','on',...
    'SortMethod','childorder','TickDir','out','FontWeight',...
    'bold','FontSize',ZmapGlobal.Data.fontsz.m,'Linewidth',1.2)

grid
hold off
done

function callbackfun_001(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =3;
  eval(cal6);
end
 
function callbackfun_002(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =6;
  eval(cal6);
end
 
function callbackfun_003(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =9;
  eval(cal6);
end
 
function callbackfun_004(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =12;
  eval(cal6);
end
 
function callbackfun_005(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =14;
  eval(cal6);
end
 
function callbackfun_006(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =18;
  eval(cal6);
end
 
function callbackfun_007(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ZG.ms6 =24;
  eval(cal6);
end
 
function callbackfun_008(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ty1='.';
  ty2='.';
  ty3='.';
  eval(cal6);
end
 
function callbackfun_009(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ty1='+';
  ty2='o';
  ty3='x';
  eval(cal6);
end
 
function callbackfun_010(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  ty1='*';
  ty2='*';
  ty3='*';
  eval(cal6);
end
 
function callbackfun_011(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  set(deplo1,'visible','off');
  set(deplo2,'visible','off');
  set(deplo3,'visible','off');
   ;
end
 
end
