report_this_filefun(mfilename('fullpath'));

catSave =...
    [ 'zmap_message_center.set_info(''Save Data'',''  '');think;',...
    '[file1,path1] = uigetfile(fullfile(ZmapGlobal.Data.data_dir, ''*.mat''), ''Earthquake Datafile'');end;',...
    'if length(file1) > 1 , sapa2 = [''save '' path1 file1 '' a faults main mainfault coastline  ''],',...
    'eval(sapa2) ,end, done'];


