function welcome(titStr, messtext)
    % This is the ZMAP welcome message
    
    report_this_filefun(mfilename('fullpath'));
    
    global mess term sys wex wey welx wely fontsz action_button c1 c2 c3
    global txtHndlList txtHndl ttlHndl
    
    clear size
    
    if nargin == 0   % reinitialize window
        
        figure_w_normalized_uicontrolunits(mess)
        messtext = '  ';
        titStr ='Messages';
        rng('shuffle');
        %if term > 1  && sys(1:3) =='SOL' ;whitebg(mess,[rand rand rand]); end
        if  sys(1:3) =='SOL'
            whitebg(mess,[c1 c2 c3]);
        end
        if    sys(1:2) =='PC'
            whitebg(mess,[c1 c2 c3]) ;
        end
        clf
        set(gca,'visible','off','SortMethod','childorder');
        set(gcf,'NumberTitle','off',...
            'Name','Message Window',...
            'MenuBar','none',...
            'Units','pixel','backingstore','off',...
            'pos',[ wex wey welx wely]);
        
        te1 = text(0.02,0.9,'Welcome to ZMAP v6.0') ;
        set(te1,'FontSize',12,'Color','k','FontWeight','bold')
        
        te2 = text(0.11,0.90,'   ') ;
        set(te2,'FontSize',fontsz.s,'Color','k','FontWeight','bold' )
        if term == 1
            whitebg(mess,[1 1 1 ]);
        end
        
        % quit button
        quit_button=uicontrol('Style','Pushbutton',...
            'Position', [.80 .60 .15 .12 ],...
            'Units','normalized',...
            'Callback','qui', ...
            'String','Quit');
            
        action_button = uicontrol(...
            'Units','normalized',...
            'BackgroundColor',[0.7 0.7 0.7 ],...
            'ForegroundColor',[0 0 0 ],...
            'Position',[0.26 0.60 0.50 0.12 ],...
            'String','   ',...
            'Style','pushbutton',...
            'Visible','on',...
            'UserData',['frame1']);
        
        set(gcf,'Units','normalized');
        txt1 = text(0.40, 0.80,'Action:','Units','Norm','FontSize',fontsz.l,...
            'Color','r','FontWeight','bold');
        
        % Display the message text
        %
        top=0.55;
        left=0.05;
        right=0.95;
        bottom=0.05;
        labelHt=0.050;
        spacing=0.05;
        
        % First, the Text Window frame
        frmBorder=0.02;
        frmPos=[left-frmBorder bottom-frmBorder ...
            (right-left)+2*frmBorder (top-bottom)+2*frmBorder];
        uicontrol( ...
            'Style','frame', ...
            'Units','normalized', ...
            'Position',frmPos, ...
            'BackgroundColor',[0.5 0.5 0.5]);
        % Then the text label
        labelPos=[left top-labelHt (right-left) labelHt];
        ttlHndl=uicontrol( ...
            'Style','text', ...
            'Units','normalized', ...
            'Position',labelPos, ...
            'BackgroundColor',[0.5 0.5 0.5], ...
            'ForegroundColor',[1 0 0], ...
            'String',titStr);
        
        %messtext=eval(['messtext')]);
        txtPos=[left bottom (right-left) top-bottom-labelHt-spacing];
        txtHndlList=uicontrol( ...
            'Style','edit', ...
            'Units','normalized', ...
            'Max',20, ...
            'String',messtext, ...
            'BackgroundColor',[1 1 1], ...
            'Visible','off', ...
            'Position',txtPos);
        set(txtHndlList(1),'Visible','on');
        %startmen(mess);
    end % if nargin == 0
    
    if nargin == 2    % text display only
        try
            set(txtHndlList(1), 'String', messtext);
            set(ttlHndl, 'String', titStr)
        catch
            welcome
        end
    end
end
