zmap_message_center.set_info('Message','Please set my_dir to your working directory!!!!');
report_this_filefun(mfilename('fullpath'));

% make the interface
%
fignum = figure_w_normalized_uicontrolunits(...
    'Name','Enter your working directory',...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'NextPlot','new', ...
    'units','points',...
    'Visible','off', ...
    'Position',[ wex+100 wey-100 250 100]);
axis off


my_dir_field=uicontrol('Parent', fignum,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[.05 .50 .90 .20],...
    'Callback','my_dir=get(my_dir_field,''String''); set(my_dir_field,''String'',my_dir);');


done_button=uicontrol('Parent', fignum,...
    'Style','Pushbutton',...
    'Units','normalized',...
    'Position',[.40 .05 .30 .20 ],...
    'Callback','close;done',...
    'String','Done');


text(...
    'Color',[0 0 0 ],...
    'Position',[0.05 .90 0 ],...
    'FontSize',fontsz.m ,...
    'FontWeight','bold',...
    'String','Please enter your working directory');

try
    cd (my_dir)
catch ME
    error_handler(ME); % @do_nothing
end

set(gcf,'visible','on');
