function zhist() % autogenerated function wrapper
% this script plots the z-values from a timecut of the map
% Stefan Wiemer  11/94
 % turned into function by Celso G Reyes 2017
 
ZG=ZmapGlobal.Data; % used by get_zmap_globals

%Find out of figure already exists
%
report_this_filefun(mfilename('fullpath'));

% This is the info window text
%
ttlStr='The Histogram Window                                ';
hlpStr1= ...
    ['                                                '
    ' This window displays all z-values displayed in '
    ' the z-value map, therefore all the z-values at '
    ' this specific cut in time for the applied      '
    'stastitical function.                           '];

think
watchon
[existFlag,figNumber]=figure_exists('Histogram',1);
newhistWindowFlag=~existFlag;
%
% Set up the Cumulative Number window

if newhistWindowFlag
    hi= figure_w_normalized_uicontrolunits( ...
        'Name','Histogram',...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'NextPlot','new', ...
        'Visible','off', ...
        'Position',[ 200 100 (ZmapGlobal.Data.map_len - [200 200]) ]);


end % if fig exist

figure_w_normalized_uicontrolunits(hi);
clf
uicontrol('Units','normal',...
    'Position',[.0  .75 .12 .09],'String','Close ',...
     'callback',@callbackfun_001)

uicontrol('Units','normal',...
    'Position',[.0  .90 .12 .09],'String','Print ',...
     'callback',@callbackfun_002)

set(gca,'visible','off','FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','bold',...
    'FontWeight','bold','LineWidth',1.5,...
    'Box','on')

uicontrol('Units','normal',...
    'Position',[.0 .60 .12 .09],'String','Info ',...
     'callback',@callbackfun_003)

matdraw
orient tall
rect = [0.25,  0.18, 0.60, 0.70];
axes('position',rect)
hold on
[m,n] = size(re3);
reall = reshape(re3,1,m*n);
l = isnan(reall);
reall(l) = [];
[n,x] =hist(reall,30);
bar(x,n,'k');
grid
xlabel('z-value','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m) %what is lab1, at the moment just print 'z-value'
ylabel('Number ','FontWeight','bold','FontSize',ZmapGlobal.Data.fontsz.m)

%title([name ' (' in '); ' num2str(t0b) ' to ' num2str(teb) ' - cut at ' num2str(it)],'FontSize',ZmapGlobal.Data.fontsz.s,...
%'Color','r','FontWeight','normal')



set(gca,'visible','on','FontSize',ZmapGlobal.Data.fontsz.m,'FontWeight','bold',...
    'FontWeight','bold','LineWidth',1.5,...
    'Box','on')
set(hi,'Visible','on');
figure_w_normalized_uicontrolunits(hi);
%watchoff(zmap);
watchoff;done


function callbackfun_001(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  close(hi);
end
 
function callbackfun_002(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  myprint;
end
 
function callbackfun_003(mysrc,myevt)
  % automatically created callback function from text
  callback_tracker(mysrc,myevt,mfilename('fullpath'));
  zmaphelp(ttlStr,hlpStr1);
end
 
end
