function initialize

addpath('~/zmap/src/thomas:', ...
     '~/zmap/src/thomas/synthetic:', ...
     '~/zmap/src/thomas/decluster:', ...
     '~/zmap/src/thomas/decluster/gardnerknopoff:', ...
     '~/zmap/src/thomas/decluster/marsan:', ...
     '~/zmap/src/thomas/decluster/reasen:', ...
     '~/zmap/src/thomas/etas:', ...
     '~/zmap/src/thomas/gui:', ...
     '~/zmap/src/thomas/plot:', ...
     '~/zmap/src/thomas/pov:', ...
     '~/zmap/src/thomas/seismicrates:', ...
     '~/zmap/src/thomas/seismicrates/ex:', ...
     '~/zmap/src/thomas/synthetic:', ...
     '~/zmap/src/thomas/ex:', ...
     '~/zmap/results:', ...
     '~/zmap/eq_data:', ...
     '~/zmap/eq_data/Alaska:', ...
     '~/zmap/eq_data/Adak:', ...
     '~/zmap/eq_data/SCEC:', ...
     '~/zmap/eq_data/Shearer:', ...
     '~/zmap/eq_data/Taiwan:')
